### ISSUE TITLE
求助！想在小程序里面做跳转

### ISSUE THREAD

**Issue by AlienC** [sbfkcel/towxml#10]
想在小程序里面做内部跳转，在后台编辑文章，想在关键字上加上小程序内的链接，在小程序里面实现跳转。

例如在后台：
`<a href="/pages/index/index">关键字</a>`

小程序里面没有把这个 href  链接转换成 navigator 里的 url的链接。

我想问下，这个如果改插件需要怎么改？

**Comment by sbfkcel** [comment]
在html里面自行添加url属性是否可取呢？

**Comment by sbfkcel** [comment]
@AlienC 新版本已经处理了。

**Comment by sbfkcel** [comment]
@rentianxiang 没明白你的意思

**Comment by rentianxiang** [comment]
不好意思前面不会插入代码。。

就是我html中有这么一段代码:
`<a class="link" href="./TSB">TSB</a>`
转换成wxml之后不显示了，我想把这个作为一个bind:tap方法，参数传递href内的信息，这个可以实现吗？

**Comment by sbfkcel** [comment]
通过自定义事件去实现。参考 demo里面的代码，绑定事件的方法中能够拿到dom相关的信息。

**Comment by rentianxiang** [comment]
@sbfkcel 昨天按照demo中的代码，在微信小程序js文件中定义了`this['event_bind_touchstart'] = (event)=>{console.log(event.target.dataset._el);     // 打印出元素信息};`这个方法，可是在我点击页面时，出现没有事件绑定touchstart的错误。
Component "pages/detail/detail" does not have a method "__bind_touchstart" to handle event "touchstart".
