### ISSUE TITLE
wepy build 提示 Missing files: fs in xx……/src/towxml/outTemplate.js

### ISSUE THREAD

**Issue by meibin08** [sbfkcel/towxml#100]
+ 系统：mac
+ wepy :1.7.2
+ 项目 npm run dev  或者 build 都会提示 [Error] Missing files: fs in /Users/xx/applets/src/towxml/outTemplate.js
手动 `npm i fs  ` 一次后，还是会报，
求解决方案，fs属于node自带的，应该不用安装才对～

![image](https://user-images.githubusercontent.com/18324563/70790012-1a021000-1dcf-11ea-864f-d841ee949fad.png)

## 后续
直接使用demo 也有同样的问题，
npm run dev的时候会报这个错，但跳过了，不显示开发
npm run build 也一样报这错，但影响了最后的输出，导致项目不能运行～

**Comment by sbfkcel** [comment]
这个文件可以删掉，仔细看下说明

**Comment by guxiaojie** [comment]
看一下是不是自动引入了
import { constants } from 'fs';
删掉
