### ISSUE TITLE
markdown图片转换并在小程序中渲染的格式

### ISSUE THREAD

**Issue by rentianxiang** [sbfkcel/towxml#103]
需要转换的markdown有如下语句:
`[http://xx.xx.xx.xx/images/6/69/MOS_platform.png](./Http://xx.xx.xx.xx/images/6/69/MOS_platform.png)`
我理解后面小括号内的地址是wxml将要渲染的图片地址对吗？由于这个地址是错误的，我用replace将小括号内的地址改成了中括号内的再进行wxml的转换，结果图片还是无法渲染。

**Comment by sbfkcel** [comment]
小程序需要https哟，并且域名要你有添加到白名单，如果还是不行。

**Comment by rentianxiang** [comment]
我是在开发者工具里调试的，并且勾选了“不校验合法域名”。

很奇怪的是,转换前我已经将markdown中的图片地址转换成了下面的绝对地址，还是无法解析，只会解析出 '[http://xx.xx.xx.xx/images/6/69/MOS_platform.png]' 这个字符串，后面的图片没有。

`[http://xx.xx.xx.xx/images/6/69/MOS_platform.png](http://xx.xx.xx.xx/images/6/69/MOS_platform.png)`

**Comment by sbfkcel** [comment]
图片的标签是
`![alt]('http://xx.png')`

**Comment by rentianxiang** [comment]
图片可以显示了，感谢作者！
