### ISSUE TITLE
请问towxml怎么支持Taro框架下Typescript+React？有没有相关的是示例，谢谢。

### ISSUE THREAD

**Issue by gltomorrow** [sbfkcel/towxml#104]

**Comment by sbfkcel** [comment]
参考这个

**Comment by gltomorrow** [comment]
感谢回复！我看过这个实现。 这个是基于Taro+React ，使用Typescript 还是有问题。





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by sbfkcel** [comment]
新版本可移植性增强。可查看demo
