### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by Hbingbing** [sbfkcel/towxml#107]
想请问下，能否根据图片的大小，自动显示图片的宽度。
如果图片的宽度小于屏幕的宽度，则根据图片的实际尺寸展示，如果图片的宽度大于或等于屏幕的宽度，则width:100% 显示。
现在就是如果图片太小，不希望被放大，因为会糊掉。

**Comment by sbfkcel** [comment]
可以自行给图片指定宽高

**Comment by Hbingbing** [comment]
直接解析md呢？因为md的格式是类似： ![示例图片](/image/xxx.png)

**Comment by Hbingbing** [comment]
直接解析md呢？因为md的格式是类似：`![示例图片](/image/xxx.png)`

**Comment by sbfkcel** [comment]
这个暂时不行，我看下个版本中改善下吧。

**Comment by sbfkcel** [comment]
```plantuml
@startuml component
actor client
node app
database db

db -> app
app -> client
@enduml
```

**Comment by ZeeMenng** [comment]
> 直接解析md呢？因为md的格式是类似：`![示例图片](/image/xxx.png)`

这个问题有最新的解决方案了没？

**Comment by Hbingbing** [comment]
您好，我是黄冰纯。您的邮件我已经收到，我会尽快查看的，谢谢~~祝您生活愉快~~
