### ISSUE TITLE
能否支持小程序云开发存储的fileID

### ISSUE THREAD

**Issue by Bill66888** [sbfkcel/towxml#108]
试了一下markdown代码中引用微信小程序云开存储的图片：[](cloud://shedeshushurelease-60436b.7368-shedeshushurelease-xxxxx-1257613110/kits/a7r2zl01/幻灯片15.PNG)
运行时会出现：
Failed to load local image resource /pages/dark/cloud://shedeshushurelease-60436b.7368-shedeshushurelease-xxxxx-1257613110/kits/a7r2zl01/%E5%B9%BB%E7%81%AF%E7%89%8715.PNG 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
看上去路径前面被加了个前缀：/pages/dark/，如果程序能识别出来cloud://，而不加路径前缀，是不是就可以显示云存储fileID的图片了。这样可以不用对外暴露图片。。。

**Comment by sbfkcel** [comment]
小程序本身不直接支持`cloud://`的协议，你需要将云地址转成实际的文件地址。

`https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-http-api/storage/batchDownloadFile.html`
