### ISSUE TITLE
一些emoji 不显示，还有一些不应该的换行

### ISSUE THREAD

**Issue by JaimeCheng** [sbfkcel/towxml#109]
1. emoji有些不显示
![image](https://user-images.githubusercontent.com/22406024/71729763-7f4f9b00-2e7b-11ea-850b-804ad4abe862.png)
2. 上图 还有这个
![image](https://user-images.githubusercontent.com/22406024/71729793-955d5b80-2e7b-11ea-8ff6-629cc7b4f80d.png)
都是原本没有换行的

**Comment by JaimeCheng** [comment]
作者要不要考虑一下  html 和 markdown 分离的啊 😉体积会小一点

**Comment by sbfkcel** [comment]
体积的问题会在近期发布的版本中解决一系列问题

**Comment by sbfkcel** [comment]
不支持的emoji能帮忙列出来下吗？

**Comment by JaimeCheng** [comment]
我就试了两个 有一个`:bowtie:` 
![image](https://user-images.githubusercontent.com/22406024/71763523-d145fe80-2f17-11ea-9ba3-b7aa01bdbe79.png) 
不支持不知道是不是巧合  🤢。您能帮我解决下换行的问题吗？😅 然后问问您 新版本 有啥大的更新吗 很期待！

**Comment by sbfkcel** [comment]
文本显示 不下会自动换行。完全没有问题的呀。

**Comment by JaimeCheng** [comment]
不是的  ，😂
![image](https://user-images.githubusercontent.com/22406024/71763656-46fe9a00-2f19-11ea-98dd-0ef93cdf87d7.png)
您看图片，就是比如加粗 或者删除线后 就换行了，原本是在一行的 ，原本是这样的
![image](https://user-images.githubusercontent.com/22406024/71763769-a9a46580-2f1a-11ea-80d9-65eec3504c87.png)
![image](https://user-images.githubusercontent.com/22406024/71763771-b1fca080-2f1a-11ea-9d20-e8538e2d2ad6.png)

**Comment by sbfkcel** [comment]
emoji显示的问题已经处理，按 https://emoji.muan.co/ 这里来的。

换行的问题，是字符在有修饰之后导致的。贴一下你的markdown字符内容吧。
