### ISSUE TITLE
towxml 3.0中模板中如何使用

### ISSUE THREAD

**Issue by hirCodd** [sbfkcel/towxml#111]
RT，towxml3.0模板是如何使用的呢？貌似与2.0有很多不同啊。有没有一份示例呢。谢谢~~~ @sbfkcel

**Comment by sbfkcel** [comment]
看wiki有文档

https://github.com/sbfkcel/towxml/wiki/3.0-%E8%AE%A9Demo%E8%B7%91%E8%B5%B7%E6%9D%A5
