### ISSUE TITLE
图片显示不正常

### ISSUE THREAD

**Issue by samsara2011** [sbfkcel/towxml#112]
html里自带的图片有指定大小，现在解析后图片全部扩大大整个页面，未能按正常大小显示。

[1 水力学.zip](https://github.com/sbfkcel/towxml/files/4089884/1.zip)

**Comment by sbfkcel** [comment]
拉取下最新版本，应该已经修复了。

**Comment by samsara2011** [comment]
收到了，已解决，感谢！感谢！
