### ISSUE TITLE
<towxml nodes="{{question}}" /> 不能够正确转换成对应的 wxml

### ISSUE THREAD

**Issue by pumpkin0** [sbfkcel/towxml#119]
**现象：**
question是题干信息，其包含公式，公式一定概率不能够正确转换，其余文字部分没问题。

**业务场景：**
小程序的swiper-item中嵌套题目，swiper-item滑动展示不同题目。题干信息中的公式在每隔3个题目就会重复出现。但是各个题干（question）中的公式是不一样的，不应该重复。

**示例：**
![image](https://user-images.githubusercontent.com/32666933/75610621-c55c6e80-5b4d-11ea-94b0-db336461f97c.png)
以上控制台打印的是正确的公式（应该是有编码，你应该能看懂），也是question的公式实际值，但是页面解析出来的是错误的（错误公式是之前题目中的）。

正确的题目如下显示：
![image](https://user-images.githubusercontent.com/32666933/75610667-30a64080-5b4e-11ea-96da-bf5d4d97fb07.png)
以上，描述结束。

麻烦帮忙看一下，我怀疑是 
"usingComponents": {
    "towxml": "/towxml/towxml"
  }
这个组件在解析的时候有问题，是不是缓存过之前的公式，导致取值时出现了错误。
非常感谢！

**Comment by samsara2011** [comment]
![微信图片_20200301001328](https://user-images.githubusercontent.com/6411208/75611033-9f38cd80-5b51-11ea-8660-f0c5b2fc0d99.png)

**Comment by sbfkcel** [comment]
经过验证不是towxml的问题。检查swiper的传入数据是否正确。
