### ISSUE TITLE
导入默认demo后模拟器一直转圈圈

### ISSUE THREAD

**Issue by lcuwx2016** [sbfkcel/towxml#12]
导入默认demo后模拟器一直转圈圈

**Comment by sbfkcel** [comment]
看一下控制台，是否是网络请求错误。因为示例文档是在github上的。

**Comment by lcuwx2016** [comment]
发现了，是小程序的问题，小程序中的released网址必须备案。。。我换了我腾讯云机器可以了

Fried rice <notifications@github.com> 于2018年5月6日周日 下午10:15写道：

**Comment by sbfkcel** [comment]
OK
