### ISSUE TITLE
怎么增加新的语言高亮支持呢？比如C等其它语言

### ISSUE THREAD

**Issue by nireus1997** [sbfkcel/towxml#120]

**Comment by sbfkcel** [comment]
- 在此![下载](https://github.com/highlightjs/highlight.js/tree/master/src/languages)你要支持的语言
- 并将文件放到 towxml 的 `parse/highlight/` 目录中，例如`c.js`
- 修改 towxml 的`config.js` 文件，在 `highlight` 项添加 `c`（与上方文件名对应）
- 重新构建

**Comment by nireus1997** [comment]
TKS~
