### ISSUE TITLE
转 html 的时候，行内样式被解析成了 class?

### ISSUE THREAD

**Issue by guooni** [sbfkcel/towxml#122]
**您好，非常感谢您及您的这个项目！**
最近在用这个项目的时候遇到一个奇怪的问题，就如标题所说的，转成 html 的时候，行内的样式被解析成了 class。
我下载并运行了 DEMO ，但是 DEMO 使用的是 markdown，并没有转 html 的示例，我尝试在您提供的 DEMO 中转 html，也是出现了上述的情况。
下面参考的图片：
![image](https://user-images.githubusercontent.com/46471562/76207203-4abfdd00-6238-11ea-953b-912ada314d72.png)
![image](https://user-images.githubusercontent.com/46471562/76207243-5c08e980-6238-11ea-9ed5-7e781ad777af.png)

**Comment by sbfkcel** [comment]
![image](https://user-images.githubusercontent.com/5469785/76212066-a000ec00-6242-11ea-965d-02ec3398aa02.png)
并没有出现你说的情况。

方便把你的代码发一份儿吗？

**Comment by guooni** [comment]
感谢您的回复，我新建了一个demo，发现还是一样的问题，所以得麻烦您看看代码了，不知道我哪里出了问题。
[demo](https://github.com/guooni/towxml-demol)

**Comment by sbfkcel** [comment]
我下载不了你的demo，打个压缩包发上来吧。

**Comment by sbfkcel** [comment]
![Snipaste_2020-03-10_14-26-03](https://user-images.githubusercontent.com/5469785/76285612-2406b280-62db-11ea-891c-acc27c242da6.png)
检查`p`与`style`之间的空格。英文，半角的空格。

**Comment by guooni** [comment]
厉害厉害。。。
还真是空格导致的，非常感谢
