### ISSUE TITLE
关于build时候的一个小bug

### ISSUE THREAD

**Issue by zhangshengran** [sbfkcel/towxml#123]
如果克隆项目的时候，把仓库克隆到了桌面（windows），然后npm i 后进行  npm build，这时会把本身的仓库删掉，然后报错，俩个原因吧，一个是因为build完的包是和仓库同名的，第二个原因是在build的时候会先删除原先build过的包，然后导致直接把仓库都删掉了。。。
![image](https://user-images.githubusercontent.com/26033802/76285237-392f1180-62da-11ea-9f1b-c5a66498278d.png)

**Comment by sbfkcel** [comment]
之后处理，你先不要克隆到桌面。当时把结果生成到桌面的原因是为了让用户方便拿到build结果。

**Comment by zhangshengran** [comment]
恩，好的。其实一样的，个人建议是把打包放到自己项目下面，平时好像习惯去项目下面找dist或者build了。
