### ISSUE TITLE
标点符号居中问题，

### ISSUE THREAD

**Issue by gongyuan303** [sbfkcel/towxml#129]
![image](https://user-images.githubusercontent.com/30801250/77848636-b9b9a180-71f8-11ea-8b78-defd11ae41c7.png)
图片中标识红色部分
使用3.0 2.0 的demo在苹果6sp上面小程序上标点符号不正确 居中显示不是在下面的

**Comment by gongyuan303** [comment]
请问群主 这是为什么

**Comment by sbfkcel** [comment]
已修复

**Comment by gongyuan303** [comment]
如何解决的，我从哪里获取最新代码

**Comment by sbfkcel** [comment]
github上的就是最新的。重构构建替换即可。
