### ISSUE TITLE
markdown标题如果超过手机屏宽，出现不友好的显示，如下图。

### ISSUE THREAD

**Issue by yicm** [sbfkcel/towxml#13]
## 3.1 Github账号注册及HTTPS/SSH连接方式介绍Github账号注册及HTTPS/SSH连接方式介绍Github账号注册及HTTPS/SSH连接方式介绍Github账号注册及HTTPS/SSH连接方式介绍Github账号注册及HTTPS/SSH连接方式介绍

![](https://note.youdao.com/yws/public/resource/7bc4ba4dd5e31c1ecc639062afb072c9/xmlnote/324B5644C5054B9EAF941F60CA4DFAC0/45620)

**Comment by sbfkcel** [comment]
好的，我抽空调整下。

**Comment by yicm** [comment]
👍 希望大神速度哈，哈哈，激情忘我，造福我等菜鸟。

**Comment by sbfkcel** [comment]
新版本已经更新。谢谢反馈。
