### ISSUE TITLE
html的pre和code标签转换后，左滑是不能整块滑动

### ISSUE THREAD

**Issue by WebGuHui** [sbfkcel/towxml#139]
![image](https://user-images.githubusercontent.com/11729740/81685124-650d7580-948a-11ea-94b0-ed310af351eb.png)

左滑时只滑动了单个view，在html上没有这个问题，html是

![image](https://user-images.githubusercontent.com/11729740/81685245-80788080-948a-11ea-89cd-1b4cea33b3e3.png)

**Comment by sbfkcel** [comment]
可能你的其它外部样式影响了
