### ISSUE TITLE
如果一个markdown文件中链接了另一个markdown文件链接，怎么实现跳转呢？

### ISSUE THREAD

**Issue by yicm** [sbfkcel/towxml#14]
我采用了`towxml`后，发现如标题所示情况出现错误：

```
navigateTo:fail url "pages/mdShow/https://xxx.test.com/another.md" is not in app.json
```
能否实现跳转呢？ 我尝试了(wxParse)[https://github.com/icindy/wxParse]项目，利用wxParseTagATap: function可以实现服务器上的markdown文件的跳转显示。

**Comment by sbfkcel** [comment]
towxml支持`a``href`属性解析，允许在小程序内部进行页面跳转，不知道是不是能解析你描述的问题。

**Comment by yicm** [comment]
像这种[https://xxx.test.com/another.md](https://xxx.test.com/another.md)外部链接也能支持跳转吗？ 如果支持，需要设置或者修改哪里来实现这种链接的内部页面跳转？

**Comment by sbfkcel** [comment]
@yicm 最新的版本已经支持自定义事件了，请参见说明文档『自定义事件』部分。

**Comment by yicm** [comment]
点击一个链接，比如绑定了tap，会触发两次tap事件。可能是一个是属于nvigator，一个属于page的。

**Comment by yicm** [comment]
微信小程序里面无法阻止tap这种冒泡事件吧？  https://xxx/xx.md 这种链接是在一个markdown文件里面，通过towxml解析出来的，无法去手动加data-href这种自定义属性。。

**Comment by yicm** [comment]
可以通过`event.target.dataset.href` 获取 `"https://xx.test.com/xxxx.md"`，只是page和navigator都会触发tap事件，导致连续两次进入回调函数，虽然可以通过程序逻辑来处理，不过还是不友好。规避两次连续进入逻辑：

```
this['event_bind_tap'] = (event) => {
 if (that.data.is_first_tap) { 
     // do something....
 }
 that.data.is_first_tap = false;
      setTimeout(function () {
        that.data.is_first_tap = true;
      }, 1000);
}
```

**Comment by sbfkcel** [comment]
目前更多的用户实现的还是使用href在小程序页面中进行跳转。
如果把事件支持改成，`capture-bind:事件`和`capture-catch:事件`觉得如何？能否解决你的问题呢？
