### ISSUE TITLE
br标签的错误处理

### ISSUE THREAD

**Issue by WebGuHui** [sbfkcel/towxml#140]
br标签目前是被处理成view的，并且没有任何样式

可以处理成text标签，使用\n换行
![image](https://user-images.githubusercontent.com/11729740/81799962-ad896980-9544-11ea-887d-37646846e7c7.png)
新增br tag映射，然后在decode.wxml新增br
` <text wx:if="{{item.tag==='br'}}" data-data="{{item}}" class="{{item.attr.class}}" data="{{item.attr.data}}" id="{{item.attr.id}}" style="{{item.attr.style}}" catch:tap="_tap">\n<decode wx:if="{{item.child}}" nodes="{{item}}" /></text>`

**Comment by sbfkcel** [comment]
没必要为换行再额外多加一断模版。view 是 block 本身就起到了换行的作用。

**Comment by WuXianShi** [comment]
> 没必要为换行再额外多加一段模版。view 是 block 本身就起到了换行的作用。

但是如果要实现空出多行呢？光view换行实现不了啊

**Comment by sbfkcel** [comment]
> > 没必要为换行再额外多加一段模版。view 是 block 本身就起到了换行的作用。
> 
> 但是如果要实现空出多行呢？光view换行实现不了啊

这个需求有点奇怪 。  如果 要空一大块距离，使用 padding 或 margin 去实现不更简洁吗？

**Comment by WuXianShi** [comment]
> > > 没必要为换行再额外多加一段模版。view 是 block 本身就起到了换行的作用。
> > 
> > 
> > 但是如果要实现空出多行呢？光view换行实现不了啊
> 
> 这个需求有点奇怪 。 如果 要空一大块距离，使用 padding 或 margin 去实现不更简洁吗？

和我用的编辑器有关吧，其用的是br来实现换行的【捂脸哭】
