### ISSUE TITLE
不知如何解析来自微信公众号的视频组件

### ISSUE THREAD

**Issue by SmRobots** [sbfkcel/towxml#149]
·从微信公众号中获取网页源码，通过转化可以解析图片，但是还是解析不了视频，视频无法在小程序上显示

**Comment by sbfkcel** [comment]
你看 下把 video 解析成什么了？是不是视频地址被微信限制 了。

**Comment by SmRobots** [comment]
`<p>海贼王：</p><p><img class="rich_pages" data-ratio="0.5625" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNavHBBBUFD3spGf8ibe4jxoAKYQRkbozuklxXIwMFp0ajOWO31fk6HflA/640?wx_fmt=png" data-type="png" data-w="1920" style=""  /></p><p><img class="rich_pages" data-ratio="1.5" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNatxfibTuJmtsRJSxlSn2rUAphRExpp0OicQqtmYQ9OgLdicicrpjBUmrGqg/640?wx_fmt=jpeg" data-type="jpeg" data-w="640" style=""  /></p><p><img class="rich_pages" data-ratio="0.45517241379310347" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNaaevDYF89C4a3WdMicxbk7mmazdJuhsO4ib9hnXdVQ5q3skqnCTc8Oy5Q/640?wx_fmt=jpeg" data-type="jpeg" data-w="580" style=""  /></p><p><img class="rich_pages" data-ratio="0.5625" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNaQ4xEpJxQUJYow2Rf4laueUY3yfjD6mL8gtIG0FhNUCgWRv4UjLIpHA/640?wx_fmt=jpeg" data-type="jpeg" data-w="1280" style=""  /></p><p><img class="rich_pages" data-ratio="0.5625" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNaBeqxEe9BIZp5dc3fegg4uUSSclaUpPUOY4sHfxfMvgSxuWtiaM2qhaw/640?wx_fmt=jpeg" data-type="jpeg" data-w="1280" style=""  /></p><p><img class="rich_pages" data-ratio="0.5625" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNa0X6WYU16qr6PwzzkjZM46rOvbAg2qQ4jTOZoelQ2TldOpCxxJicLO7w/640?wx_fmt=jpeg" data-type="jpeg" data-w="1280" style=""  /></p><p><img class="rich_pages" data-ratio="1.7775862068965518" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/AGEsLhUibZWEHLBjZIt9X9dCds2ZGctNaA8597244DKokYFo2qibsJkQW9KwWvVKIia08JJjufbZLW22njyU4Ncmw/640?wx_fmt=jpeg" data-type="jpeg" data-w="580" style=""  /></p><p>下面是一个视频</p><p><iframe class="video_iframe rich_pages" data-vidtype="2" data-mpvid="wxv_1327899987077922817" data-cover="http%3A%2F%2Fmmbiz.qpic.cn%2Fmmbiz_jpg%2FAGEsLhUibZWEHLBjZIt9X9dCds2ZGctNafZ4Pib472ug47eUicKRFpIeRdxON7My1byibjTla1iahKAwvT3JHOjpqjw%2F0%3Fwx_fmt%3Djpeg" allowfullscreen="" frameborder="0" data-ratio="1.7777777777777777" data-w="1280" data-src="https://mp.weixin.qq.com/mp/readtemplate?t=pages/video_player_tmpl&amp;action=mpvideo&amp;auto=0&amp;vid=wxv_1327899987077922817"></iframe></p><p><br /></p>
`

这个是我随便上传的一个图片和视频的html,通过公众号获取出来的，请问能帮我看一下这个内容吗？

**Comment by sbfkcel** [comment]
你这个里面哪包含视频了？
