### ISSUE TITLE
uniapp中引入towxml后，公式没有解析，还是原样的。

### ISSUE THREAD

**Issue by canknow** [sbfkcel/towxml#151]
这是公式$\sqrt{7}$，按照html解析的。parse后的这个公式节点类型是text，内容还是这个。

**Comment by canknow** [comment]
我排查过了 发现需要设置成markdown，不能是html，且不能有div标签，才能解析出来。测试字符串：
<div class="ques_border"><img  src="http://qz-question.oss-cn-beijing.aliyuncs.com/rep%2F3m%2Fd811b33bc639955c460268819c1d2b.png" style="vertical-align:middle;;"><p class="ocr_text_invisible"> VB </p><span class="qseq"></span><p>如图，四棱锥S-ABCD中，AB∥CD，BC⊥CD，侧面SAB为等边三角形，AB=BC=2，CD=1，SD=<span class="latex">$\sqrt{7}$</span>．<br>（1）证明：平面SAB⊥平面ABCD；<br>（2）求点A到平面SDC的距离．</p></div>

**Comment by sbfkcel** [comment]
`$\sqrt{7}$`是属于 markdown 的公式表达方式

在 html 中要支持公式方式的解析格式为：

```html
<latex value="\sqrt{7}" type="line"></latex>
```

或

```html
<latex value="\sqrt{7}" type="block"></latex>
```

yuml 流程图则为：

<yuml value=""></yuml>

**Comment by canknow** [comment]
是啥意思呢 是我html内容要自己把HTML中的$\sqrt{7}$替换成<latex></latex>标签再显示么。

**Comment by sbfkcel** [comment]
是的呢

**Comment by canknow** [comment]
谢谢了。把html中的公式转换成latex标签后，发现image请求了两次接口，第一次请求tex=\sqrt{7}，第二次tex=sqrt{7}，且实际显示图片为第二次请求的结果，好奇怪，image明明只有一个标签。

**Comment by sbfkcel** [comment]
你把代码精简到最小看看， 是不是哪里重复渲染了。

**Comment by kuaileforever** [comment]
请问这个问题是什么原因导致的呢，我这边也出现了请求2次接口，最后一次\被删除了导致图片解析不对。

**Comment by mjkohoh** [comment]
我这边也出现了2次请求
