### ISSUE TITLE
markdown 模式下，如果公式前有html标签则会影响显示

### ISSUE THREAD

**Issue by chengaojian** [sbfkcel/towxml#153]
例如：
`<p>这是标签内容</p> $\\frac{1}{2}+\\frac{3}{4}$  测试数学公式在手机上的展示`（更新一下）
如果带有html标签在latex之前，则公式将无法正常渲染出来，是我使用姿势不对，还是不支持这种组合形式？

**Comment by sbfkcel** [comment]
支持的。你的公式明显是错的呀。看一下 demo 中的公式输入。

**Comment by chengaojian** [comment]
> 支持的。你的公式明显是错的呀。看一下demo中的公式输入。

不好意思，这个问题编辑的时候中间干了点别的事导致公式没有写全，但是经过多次测试，确实是不支持的，标签在后面的支持，但是一旦标签放到latex前面就不行了，就会导致后面的显示不全，你那边可以亲自试一下可以用我这段测试： "<p>这是标签内容</p> $\\frac{1}{2}+\\frac{3}{4}$  测试数学公式在手机上的展示"

**Comment by chengaojian** [comment]
或者你那边不好复现的话可以联系我，我QQ:962131500

**Comment by sbfkcel** [comment]
在 markdown 中正确的输入会是：

```markdown
<p>这是标签内容</p> 

$\\frac{1}{2}+\\frac{3}{4}$ 测试数学公式在手机上的展示（更新一下）
```

你如果要解析 html 又要支持公式的话。参见：https://github.com/sbfkcel/towxml/issues/138

**Comment by chengaojian** [comment]
> 在markdown中正确的输入会是：
> 
> ```gfm
> <p>这是标签内容</ p> 
> 
> $ \\ frac {1} {2} + \\ frac {3} {4} $测试数学公式在手机上的展示（更新一下）
> ```
> 
> 你如果要解析html又要支持公式的话。参见：[＃138](https://github.com/sbfkcel/towxml/issues/138)

我试了，好像还是不行，不知道我没理解对你的意思，还是我操作不对，能否留个联系方式，耽误你一点时间，谢谢

**Comment by simsimiSION** [comment]
@chengaojian 亲，这个问题您解决了吗

**Comment by chengaojian** [comment]
没，我暂时是通过其他方式规避这种问题了


| |
陈高健
|
|
邮箱：j_mailbox@163.com
|

签名由 网易邮箱大师 定制

在2020年07月12日 02:55，simsimi 写道：

@chengaojian 亲，这个问题您解决了吗

**Comment by sbfkcel** [comment]
这种问题是自身的问题。严格的markdown是不允许再包含html，但现在很多第三方编辑器也支持这么混着用。
即使是这样，也是对内容格式有所要求。

注意内容之间的换行。
