### ISSUE TITLE
markdown 的代码块，在真机上横向滚动失效

### ISSUE THREAD

**Issue by CK110** [sbfkcel/towxml#16]
模拟器上有滚动

**Comment by XiaoBaiAI** [comment]
```c++
#include <stdio.h>

int main(int argc, char *argv[])
{
    printf("hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!hello world!");

    return 0;
}
```

超过一定长度就不能横向滚动了，真机上会自动换行，没有横向滚动条出现。

**Comment by sbfkcel** [comment]
自动换行没毛病吧。真机跟模拟器稍有差别是正常的。~~晚些我看看，应该是强制换行的。

**Comment by yicm** [comment]
滚动条好看点，不会改变原来个代码编排风格

**Comment by sbfkcel** [comment]
测试过模拟器和真机上均无问题。

**Comment by yicm** [comment]
@sbfkcel 苹果没测试丫。。在iphone上不行哦。。

**Comment by CK110** [comment]
mac环境下小程序ide的模拟器是可以的，iphone真机上不行

**Comment by sbfkcel** [comment]
**iPhone真机截图：**

![wechatimg3](https://user-images.githubusercontent.com/5469785/40850511-5a2d6c56-65f7-11e8-88e3-a4f5d9fba493.png)

**代码片段：**

![snipaste_2018-06-01_23-55-16](https://user-images.githubusercontent.com/5469785/40850496-4f6bea2c-65f7-11e8-8fcf-2709e73ead3e.png)

**Comment by yicm** [comment]
测试环境： ios

**模拟器效果(有滚动条)：**
![](https://note.youdao.com/yws/public/resource/7bc4ba4dd5e31c1ecc639062afb072c9/xmlnote/EE425C82379A49D084B4C9AD0661D25F/45942)

**真机效果(无滚动条)：**

![](https://note.youdao.com/yws/public/resource/7bc4ba4dd5e31c1ecc639062afb072c9/xmlnote/3B5510CE0FBF4970AC6AE57594170620/45943)

**Comment by sbfkcel** [comment]
@yicm 贴一下你的内容片段吧。

**Comment by yicm** [comment]
**只要代码段里面的一行超过行距就应该出现滚动条**

```
# 第一步：合并分支时发生了冲突(conflict)
# 第二步：查看当前冲突情况
$ git status
# On branch branch-b
# You have unmerged paths.
	#   (fix conflicts and run "git commit")
	#
	# Unmerged paths:
	#   (use "git add ..." to mark resolution)
	#
	# both modified:      test_conflict.txt
	#
no changes added to commit (use "git add" and/or "git commit -a")
# 第三步：打开冲突的文件，并进行修改，保留你想要的内容
# 通过搜索冲突标记符号<<<<<<<，可以快速定位冲突位置
# <<<<<<< HEAD  到 =======标记符号之间为一个分支修改内容
# ======= 到 >>>>>>>为另一个分支修改内容
# 保留你想要保留的内容，然后删除所有的标记符号
# 第四步：修改完冲突文件后，将修改文件添加到仓库跟踪中
$ git add -A
# 第五步：解决完冲突，提交内容
$ git commit -m "Resolved merge conflict."
# 第六步：合并分支
# 第七步：推送到远端仓库，然后在远端仓库，如Github发起Merge pull request.
```

**Comment by sbfkcel** [comment]
@yicm 使用github上的最新代码看一下。应该是可以了的。
