### ISSUE TITLE
请问行内的公式，和标签内的公式。小程序能识别么，我这边好像有些出入啊～～～

### ISSUE THREAD

**Issue by Edisonzzy** [sbfkcel/towxml#160]
<img width="535" alt="截屏2020-07-23 下午6 51 06" src="https://user-images.githubusercontent.com/16329562/88278788-9077d080-cd15-11ea-9fcc-6afc747c5fc7.png">
<img width="555" alt="截屏2020-07-23 下午6 51 13" src="https://user-images.githubusercontent.com/16329562/88278798-940b5780-cd15-11ea-8b3b-5c6ada60c40a.png">

**Comment by sbfkcel** [comment]
这种直接写死的，注意符号转译。

https://github.com/sbfkcel/towxml/issues/138
