### ISSUE TITLE
如果git clone 时当前目录为桌面，将无法完成构建

### ISSUE THREAD

**Issue by shiny** [sbfkcel/towxml#162]
如果 bash 的当前目录为桌面，将 npm run build 时会清空当前目录，导致报错无法完成构建。
建议构建结果目录设置为 `towxml/dist`

**Comment by sbfkcel** [comment]
克隆的时候换个名儿。或在桌面随便创建一个临时目录。因为考虑到很多小白用户晕目录的问题。所以就直接将结果创建在桌面，方便寻找。

**Comment by shiny** [comment]
改了配置，构建一下然后整个目录都不见了，改动也没了，这已经影响到正常使用了

**Comment by shiny** [comment]
而且再小白连 build 时候不去当前 /dist 下找，我建议小白转行了

**Comment by sbfkcel** [comment]
克隆完成改名字可以的吧 `desktop/towxml` -> `desktop/test`

或是换个目录

`desktop/towxml` -> `desktop/temp/towxml`

**Comment by shiny** [comment]
讨论的不是怎么完成构建，这个昨天已经搞明白了，而是设计的合理性的问题。
如果您觉得很合理，那就 close issue 吧，谢谢。

**Comment by sbfkcel** [comment]
嗯。也确实多个用户遇到这情况。我稍微处理一下
