### ISSUE TITLE
富文本的代码块都合并到一行了，请问怎么解决

### ISSUE THREAD

**Issue by WShuoForever** [sbfkcel/towxml#163]

**Comment by sbfkcel** [comment]
问题描述不完整，先看示例吧。

**Comment by xiaojingchuangtianya** [comment]
在样式里搜索这个内容 .h2w__pre .h2w__code

修改为这样就可以了
.h2w__pre .h2w__code {
    white-space:pre-wrap;
    width: 600px;
    display: block;
    font-size: 80%;
}

**Comment by sbfkcel** [comment]
好，解决问题就行。没猜错的话，应该是你的内容存在问题的。
