### ISSUE TITLE
我这边有个显示towxml的列表，请问怎么区别每一个的点击事件呢（或者怎么给每个towxml标签加个id）

### ISSUE THREAD

**Issue by Edisonzzy** [sbfkcel/towxml#164]
<img width="355" alt="截屏2020-08-05 下午1 10 26" src="https://user-images.githubusercontent.com/16329562/89374124-0f5d0800-d71d-11ea-9cf6-6db9ee90cdb4.png">

**Comment by sbfkcel** [comment]
![image](https://user-images.githubusercontent.com/5469785/89384158-412b9a00-d730-11ea-9764-e95dadd6eff2.png)

参考 下
