### ISSUE TITLE
两个优化建议

### ISSUE THREAD

**Issue by zjxpcyc** [sbfkcel/towxml#165]
针对与  Taro3 VUE 方式结合时的痛点提几个建议

1.  能否不要使用绝对路径?
`towxml` 必须是代码根目录, 不知道出于什么考量。这个非常不利于代码组织架构的规范。

2.  能否把 mode 与 view 分开?
我没看源码。`towxml` 的初始化, 感觉应该是纯  js 。这个应该跟 `template` 的耦合不太高。感觉分开还是有可能的。

原因:  Taro3 Vue 的原生组件支持已经很成熟，但是使用方式不完美。我必须要 `copy` 源码到 `dist` 目录。但是这个过程其实不用各种 `webpack loader` 参与。但是 Taro3 如果设置忽略 `towxml` 又会报错。因此实际生成的 `dist` 源码会有一个 `copy` 过的目录，还有散落在各组件中的经过 `loader` 的 `towxml` 。这样不利于代码压缩。基于这点，是否可以只让 `towxml` 的 `js` 部分走 `loader` 而 `template` 不走

**Comment by sbfkcel** [comment]
可以，后续版本我看怎么稍微照顾一下这些第三方框架的登录。
---
针对 Taro 这样的第三方框架，towxml官方初始并没有想去特意支持的（因为这些第三方框架每家都自己搞一套，乱七八糟。）。目前的使用方法都是用户贡献的。

**Comment by zjxpcyc** [comment]
thx
