### ISSUE TITLE
较长html渲染慢，请问有没有解决方式？

### ISSUE THREAD

**Issue by Bluesgavin** [sbfkcel/towxml#168]
需求是展示一些文档，有markdown和html的。其中有一部分用户手册长度比较长，是html格式的，在towxml渲染时很慢。           
请问：
 1. 有没有解决方式？
 2. 假如我在后台让文章切割，通过下拉加载，towxml是否支持增量渲染？
 3. 最坏打算假如我用loading遮罩，让文章渲染完成再显示。渲染完成有没有回调标识？

**Comment by sbfkcel** [comment]
1.你可以自行对文章进行分片处理。理论上是可以的。内容分片，同理渲染也分片去操作。
2.没有渲染完成的监听，只有数据解析完成。渲染是小程序本身去处理的，好像没看到有什么好的办法知道是否有渲染完成。

**Comment by Bluesgavin** [comment]
> 1.你可以自行对文章进行分片处理。理论上是可以的。内容分片，同理渲染也分片去操作。
> 2.没有渲染完成的监听，只有数据解析完成。渲染是小程序本身去处理的，好像没看到有什么好的办法知道是否有渲染完成。

好的谢谢你😁
