### ISSUE TITLE
希望加入HTML字符实体的支持

### ISSUE THREAD

**Issue by OoqwqoO** [sbfkcel/towxml#17]
如下面这段HTML，&nbsp;无法解析为空格，可参考`https://github.com/icindy/wxParse/blob/master/wxParse/wxDiscode.js`

`<p>东野圭吾  日本作家。<\/p>\n<p>&nbsp;<\/p>\n<p>1985年，《放学后》获第31届江户川乱步奖，开始专职写作；<\/p>\n<p>&nbsp;<\/p>\n<p>1999年，《秘密》获第52届日本推理作家协会奖；<\/p>\n<p>&nbsp;<\/p>\n<p>2005年出版的《嫌疑人X的献身》同时获得第134届直木奖、第6届本格推理小说大奖，并领衔三大推理小说排行榜年度排行；<\/p>\n<p>&nbsp;<\/p>\n<p>2008年，《流星之绊》获第43届新风奖；<\/p>\n<p>&nbsp;<\/p>\n<p>2009年出版的《新参者》领衔两大推理小说排行榜年度排名；<\/p>\n<p>&nbsp;<\/p>\n<p>2012年，《解忧杂货店》获第7届中央公论文艺奖；<\/p>\n<p>&nbsp;<\/p>\n<p>2013年，《梦幻花》获第26届柴田炼三郎奖；<\/p>\n<p>&nbsp;<\/p>\n<p>2014年，《祈祷落幕时》获第48届吉川英治文学奖。<\/p>\n`
![baidushurufa_2018-5-23_0-58-19](https://user-images.githubusercontent.com/18651085/40377840-7c14f102-5e24-11e8-91c0-be2c5d74ff2f.png)

**Comment by sbfkcel** [comment]
这个可以有~~我抽空加上。

**Comment by sbfkcel** [comment]
最新版本已经处理。
