### ISSUE TITLE
请问下，如果文章是英文，可以通过点击事件获得被点击的单词，并变色吗？

### ISSUE THREAD

**Issue by GuiZi** [sbfkcel/towxml#171]
请问下，如果文章是英文，可以通过点击事件获得被点击的单词，并变色吗？

谢谢！

**Comment by sbfkcel** [comment]
除非你每个单词都是被用标签包含起来。

**Comment by GuiZi** [comment]
> 除非你每个单词都是被用标签包含起来。

我也想过这样实现，但需要修改markdown.js的代码（这个代码的格式怎么就长长的一行？），而且每个单词都用标签包起来，会不会降低渲染效率？

**Comment by sbfkcel** [comment]
@GuiZi 会在一定程度上影响性能。你可以试一下。
