### ISSUE TITLE
居中无效怎么办？

### ISSUE THREAD

**Issue by zhoulei984623** [sbfkcel/towxml#174]
在PC后台编辑的时候命名是居中的
![image](https://user-images.githubusercontent.com/70946745/93770479-cf130400-fc4e-11ea-802b-d8274d665bd3.png)

在小程序显示的时候怎么解析正确？
![image](https://user-images.githubusercontent.com/70946745/93770539-e4882e00-fc4e-11ea-9dad-f5946b62aee9.png)

小程序已经对内容进行处理，如下
const markdownContent = app.towxml(advertisement.content,'markdown',{
        base:'https://cos.17bbw.com',				// 相对资源的base路径
        theme:'light',					// 主题，默认`light`,'dark'
        events:{					// 为元素绑定的事件方法
          tap:(e)=>{}
        }
      })

**Comment by sbfkcel** [comment]
改成 `<div style="text-align:center;">电话号码</div>`吧。这个标签应该没有被支持。

**Comment by zhoulei984623** [comment]
能简单说下怎么改吗？我前端不是很擅长。

**Comment by sbfkcel** [comment]
上面不是说了吗？

**Comment by zhoulei984623** [comment]
谢谢 解决了
