### ISSUE TITLE
video标签前端渲染后不能播放

### ISSUE THREAD

**Issue by zhoulei984623** [sbfkcel/towxml#178]
后端HTML代码是这样的：
<video width="100%" height="auto" controls> <source src="https://cos.17bbw.com/test.mp4" type="video/mp4"> 您的浏览器不支持Video标签。 </video>

在小程序端进行转化后可以显示播放器组件：
![image](https://user-images.githubusercontent.com/70946745/94337526-8d52d680-001d-11eb-81c0-c679d0fdb2ac.png)

但是点击播放按钮没有反应，控制台打印点击对象如下：
![image](https://user-images.githubusercontent.com/70946745/94337538-b2dfe000-001d-11eb-88fe-d94b78c15782.png)

**Comment by zhoulei984623** [comment]
控制台报错如下：
![image](https://user-images.githubusercontent.com/70946745/94337970-1ae3f580-0021-11eb-9e4f-ac9b3ac0f52f.png)

**Comment by zhoulei984623** [comment]
![image](https://user-images.githubusercontent.com/70946745/94337980-3fd86880-0021-11eb-95f7-b9e70ab5aa58.png)

**Comment by zhoulei984623** [comment]
你好 此问题已解决。  现在的问题是工具栏，没有找到video标签的插入按钮，这个要怎么做？需要添加自定义菜单按钮来实现吗？

**Comment by sbfkcel** [comment]
嗯。自定义实现吧。towxml只是作解析，对编辑器的支持自己扩展实现。
