### ISSUE TITLE
如何直接读取`.md`格式的内容

### ISSUE THREAD

**Issue by deepthan** [sbfkcel/towxml#181]
请问如何直接读取`.md`格式的内容？案例是通过http请求的，我是想写在每个页面的文件夹中，请问该如何引用。
如果将文件格式设置为js，内容写为字符串抛出来可以使用，但是需要加上很多转义的字符。
请问是否有什么简便的方式？感谢。

**Comment by sbfkcel** [comment]
一样的呀。参考小程序API文档 https://developers.weixin.qq.com/miniprogram/dev/api/file/FileSystemManager.readFile.html
