### ISSUE TITLE
可以支持下折叠语法吗

### ISSUE THREAD

**Issue by zhouyupeng** [sbfkcel/towxml#188]
可以支持下折叠语法吗

**Comment by sbfkcel** [comment]
折叠语法，对应原生的哪个？

**Comment by zhouyupeng** [comment]
> 折叠语法，对应原生的哪个？

<details>
  <summary>折叠文本</summary>
 ``` language

 \\这是代码

```
</details>

不过我已经改解析源码实现了

**Comment by sbfkcel** [comment]
OK，那能否提交个全并分支？

**Comment by zhouyupeng** [comment]
> OK，那能否提交个全并分支？

只是针对我这个特定几个语法的 不是很标准  希望大佬把这个功能加上
