### ISSUE TITLE
富文本在setdata新的富文本显示到页面的时候，第一张图片无法更新

### ISSUE THREAD

**Issue by WuXianShi** [sbfkcel/towxml#189]
如题，第一张图片还是上一段富文本的图片，不会更新为最新富文本的图片，查看回调数据图片是最新的，就是不知道为什么不能渲染到页面上

**Comment by WuXianShi** [comment]
![image](https://user-images.githubusercontent.com/63863965/110574484-24f54d00-8198-11eb-90a9-b6d9612c0e3a.png)

**Comment by sbfkcel** [comment]
先将数据设置为空，之后再设置一次正确的数据。

**Comment by WuXianShi** [comment]
好的解决了 非常感谢
