### ISSUE TITLE
代码块有注释时样式会变成斜体

### ISSUE THREAD

**Issue by afatcoder** [sbfkcel/towxml#191]
如图所示~
![1616196614(1)](https://user-images.githubusercontent.com/67673714/111851466-3552b800-894e-11eb-8745-a38451d3db81.png)

**Comment by sbfkcel** [comment]
除上具体内容

**Comment by afatcoder** [comment]
**问题描述：** 代码块中，如果出现“#”或“//”等注释类的符号，符号后的所有的代码都会变成斜体。
**问题示例：** 您提供的demo就出现了这个问题。如图，代码第4行进行了注释，5~10行的代码都成 _斜体_ 了

![1619223347(1)](https://user-images.githubusercontent.com/67673714/115940792-6e45f580-a4d5-11eb-8e58-861d386b1dfd.jpg)

**Comment by sbfkcel** [comment]
更新，已经解决
