### ISSUE TITLE
html代码出现<或者其转义符号，会解析错误

### ISSUE THREAD

**Issue by huhang2004** [sbfkcel/towxml#2]
appservice:20 thirdScriptError
undefined;at pages/article/article onLoad function;at api request success callback function
undefined
具体原因是<会解析成html标签

**Comment by sbfkcel** [comment]
@huhang2004 github上最新的代码已经修复了

**Comment by huhang2004** [comment]
`let html = _ts.md2html(mdContent),
      wxml = _ts.html2wxml(html),
      deCode = str => {
        let s = '';
        if(str.length === 0){
          return s;
        };
        s = str.replace(/&amp;/ig,'&');
        **s = s.replace(/&lt;/ig, "＜");**
        s = s.replace(/&gt;/ig, "＞");
        s = s.replace(/&nbsp;/g, " ");
        s = s.replace(/&#39;/g, "\'");
        s = s.replace(/&quot;/g, "\"");
        return s;
      };
		return deCode(wxml);
	}`
上面标粗的地方有问题，在markdown模式下，在html2json方法之前就已经替换为（<），之前在解析会当初html标签

**Comment by huhang2004** [comment]
在md2wxml方法里面 s = s.replace(/&lt;/g, "<");这个时候不应该替换，如果替换了，后面 json = _ts.m.html2json(_ts.md2wxml(content));会解析错误。
不知道我说的对不对，我刚刚碰到这样的问题

**Comment by huhang2004** [comment]
@sbfkcel 麻烦你看下

**Comment by sbfkcel** [comment]
@huhang2004 你拉取的是github上最新的代码吗？

**Comment by huhang2004** [comment]
看到了，你改成了一个特别的符号

**Comment by sbfkcel** [comment]
@huhang2004 后续版本再寻找别的办法
