### ISSUE TITLE
图片预览功能可以支持的吗？ 

### ISSUE THREAD

**Issue by yicm** [sbfkcel/towxml#20]
点击图片，可以预览，这样用户可以看缩放图的具体内容，或者可以长按识别二维码或者小程序码，很实用。

**Comment by yicm** [comment]
这功能可以的。 自定义事件怎么知道是不是点击的图片？

**Comment by yicm** [comment]
@sbfkcel 我自己修改了源码，renderTemplate.wxml，给所有的image标签都加上了`data-obj_type="image" data-image_src="{{item.attr['src']}}"` ，实现了图片预览功能。 不过请教一个问题，为啥这个文件里面有这么多image标签？ 方便加个微信以后交流吗？ emmmm，如果可以的话可以私信我邮箱yicm1102@gmail.com ，感谢。

**Comment by sbfkcel** [comment]
1.5.7版本自定义事件参数数据得到了增强。现在不需要你自行传入属性，可以很方便的获取元素的相关信息。

**Comment by yicm** [comment]
@sbfkcel 嗯嗯 不过还有一个bug要解决哈，就是点击会有两次触发效果的bug，导致需要在上层逻辑自己处理，希望这个能得到解决。具体比如tap事件:

```
this['event_bind_tap'] = (event) => {
   // 点击一次，会连续两次进入这里 
};
```

**Comment by sbfkcel** [comment]
嗯。我又更新了一个版本。间接处理掉了这些问题。

- 触发多次事件，是由于小程序的貌似机制的问题
- 重复的代码是由于小程序不支持模版相互嵌套（帮需要解析的html层级越深，模版文件就越大【默认10级】，如果你不需要解析这么深，修改`outTemplate.js`最后一行的`depth`参数，然后执行`node outTemplate.js`会生成新的模版文件）

**Comment by zhupaizhang** [comment]
请问下，点击图片预览，这边是怎么操作的。

**Comment by zhupaizhang** [comment]
无法捕捉到自定义事件，在小程序ide中提示`VM707:1 Component "pages/index" does not have a method "__bind_tap" to handle event "tap".`
