### ISSUE TITLE
预览和真机调试遇到问题无法显示

### ISSUE THREAD

**Issue by CS-liujf** [sbfkcel/towxml#205]
towxml在win的微信开发者工具中可以成功显示，但是如果使用预览或真机调试，用手机却无法成功显示，会一直处于加载状态

**Comment by sbfkcel** [comment]
确定你的内容是存在的

**Comment by CS-liujf** [comment]
> 确定你的内容是存在的

这个肯定是在的哎😂，要不然电脑的微信开发者工具也没法显示。
我不但用自己的内容做了测试，用towxml官方给的demo进行真机调试，手机也是一直显示loading转圈圈，无法把内容显示出来

**Comment by sbfkcel** [comment]
内容地址有加入白名单吗？先把内容写死，不请求网络看看

**Comment by CS-liujf** [comment]
> 内容地址有加入白名单吗？先把内容写死，不请求网络看看

数据写死的话，手机端可以正常渲染出来，但如果从网络获取数据，就只能在开发者工具里正常显示。不校验合法域名我都是设置好了的。如果预览出问题还能理解，但是真机调试也不行就很费解

**Comment by sbfkcel** [comment]
跟解析库无关。可以确定的是你的请求数据没有成功。用调试工具去看一下

**Comment by CS-liujf** [comment]
> 跟解析库无关。可以确定的是你的请求数据没有成功。用调试工具去看一下

是的，我查看了一下后端，的确没有收到来自小程序的http请求。只是我记得以前在真机调试下，可以向任意地址发送http请求。不过，谢谢你

**Comment by CS-liujf** [comment]
问题找到了，我电脑上部署的后端，url是127.0.0.1，用手机真机调试访问这个url，怎么可能发送给电脑:cry:
