### ISSUE TITLE
图片无法正常显示

### ISSUE THREAD

**Issue by CS-liujf** [sbfkcel/towxml#209]
图片markdown语句为

`![调整.jpg](https://gitee.com/strcpy-s/pic/raw/master/questions/202109021645115964.jpg)`

浏览器中可以正常打开该图片，但是手机上却无法将该图片渲染出来

**Comment by sbfkcel** [comment]
检查白名单限制

**Comment by CS-liujf** [comment]
> 检查白名单限制

经过检查，我发现的问题是，如果image标签中的src为上述地址，则网络请求的status code等于302，且response的content-type为`text/html; charset=utf-8`，所以无法显示出图片来

**Comment by sbfkcel** [comment]
跟地址无关，就是白名单限制 的问题。

**Comment by CS-liujf** [comment]
> 跟地址无关，就是白名单限制 的问题。

我用towxml的demo中的图片`https://www.vvadd.com/wxml_demo/img.jpg`，他就是正常的，request的status code为200，且content-type为`image/jpeg`，因此也能显示出图片。
微信小程序官方也说过类似的问题
[为什么图片链接可正常访问但image组件加载不出来图片？](https://developers.weixin.qq.com/community/develop/doc/000ace6189c0c03bc719a781856009)

**Comment by CS-liujf** [comment]
> 跟地址无关，就是白名单限制 的问题。

另一方面，我把https://gitee.com加入到request合法域名和downloadFile合法域名中，此问题依然存在

**Comment by sbfkcel** [comment]
gitee 也可以作来源限制

**Comment by CS-liujf** [comment]
> gitee 也可以作来源限制，被限制了来源。你一样的请求不了~

谢谢解答
