### ISSUE TITLE
采用markdown的引用标记，在里面插入图片时，图片呈现原图效果问题

### ISSUE THREAD

**Issue by yicm** [sbfkcel/towxml#21]
采用markdown的引用标记`>`，在里面插入图片时，图片呈现原图效果，影响视觉效果，可以建议将在引用标记中插入图片可以让图片的高度与文字行高保持差不多，且不能自动换行。感谢^_^。

![](https://note.youdao.com/yws/public/resource/7bc4ba4dd5e31c1ecc639062afb072c9/xmlnote/7C446B7AF2F74129A10E43572F84609E/45968)

而实际在github上的效果如下：

> ![注意](https://github.com/yicm/Images/blob/master/common/tip_32.png?raw=true) dsflsdjfsjlfjsljflkdjlfjldsjflsjf;sdfkj;lds

**Comment by sbfkcel** [comment]
这个自行修改WXSS去给图片添加类去设置图片大小。决大部分文章图片都是100%宽。

**Comment by sbfkcel** [comment]
因为
