### ISSUE TITLE
uniapp-事件监听失败

### ISSUE THREAD

**Issue by AnsonChans** [sbfkcel/towxml#210]
![image](https://user-images.githubusercontent.com/26055436/134839467-d501cbaa-9cf5-459d-aaba-cba27547f537.png)
![image](https://user-images.githubusercontent.com/26055436/134840435-03abeca1-4df3-4787-9894-9b26927b7062.png)

**Comment by sbfkcel** [comment]
请在原生基础上进行测试。这些第三方的框架需要自行移值
