### ISSUE TITLE
~（波浪号会影响渲染结果，好像被当做上下角标渲染了）

### ISSUE THREAD

**Issue by chengaojian** [sbfkcel/towxml#216]
![1](https://user-images.githubusercontent.com/15831126/145140254-ef988184-3abd-4a35-91ab-7fbbd1f6b061.png)
![2](https://user-images.githubusercontent.com/15831126/145140261-19395acd-726f-4cde-8b50-b950a8b83140.png)
如上图：
测试文本为：（思路有误）本题考察的是利用统计图获取信息，解决问题。通过观察扇形统计图和条形统计图，可知只有“15~40岁”这个年龄段有“具体人数”和“所占总人数百分比”两种信息。15~40岁的人数是144名，且占总人数的百分比为48%，所以调查的居民总人数是144÷48%=300(名)。根据老师给的思路做一做吧！

**Comment by lchtao26** [comment]
我也遇到了这个问题，波浪号之间的文本会被当成下标处理

**Comment by sbfkcel** [comment]
是的，没错就是这样的。

![image](https://user-images.githubusercontent.com/5469785/188354437-3a0dab53-4b9b-4a62-95eb-82888a1c7a58.png)
