### ISSUE TITLE
你好，请问一下这个支待办事宜TODO列表功能和字号设置吗，谢谢

### ISSUE THREAD

**Issue by zhang177177** [sbfkcel/towxml#22]
你好，请问一下这个支待办事宜TODO列表功能和字号设置吗，谢谢

**Comment by sbfkcel** [comment]
字号设置可以的哦。TODO列表是以字符形式表示的

**Comment by zhang177177** [comment]
请问如何设置字号 和todo,看到文档中没有这个说明，谢谢
https://www.cnblogs.com/muhezi/p/6486161.html#14-%E5%BE%85%E5%8A%9E%E4%BA%8B%E5%AE%9Ctodo%E5%88%97%E8%A1%A8

**Comment by sbfkcel** [comment]
已经支持
