### ISSUE TITLE
3.0真机调试错误

### ISSUE THREAD

**Issue by ghost** [sbfkcel/towxml#220]
3.0真机调试显示highlight/languages/c-like.js加载错误，开发工具显示正常

**Comment by LeslieZs** [comment]
开发工具不要更新到最新版本，回退一个版本就不会出现这个问题

**Comment by LeslieZs** [comment]
> 开发工具不要更新到最新版本，回退一个版本就不会出现这个问题

**Comment by hanyunmuyu** [comment]
> 开发工具不要更新到最新版本，回退一个版本就不会出现这个问题

我查了一下原因，因为依赖文件路径是动态生成的，微信开发工具会忽略这些动态加载的js文件 ，我直接按照路径引入就可以了。

**Comment by hanyunmuyu** [comment]
修改了这两个地方，就可以正常打包了
![{XTH2M@QWKAT`2Q888M{)KR](https://user-images.githubusercontent.com/10182096/152671843-4ab3eeff-8925-4c07-962c-964fcf511a6b.png)
![{XTH2M@QWKAT`2Q888M{)KR](https://user-images.githubusercontent.com/10182096/152671857-5b36145b-adb8-4696-b8bd-562fe6dd7836.png)

**Comment by LeslieZs** [comment]
你这样配置完之后，其他的不报错吗？

**Comment by zx86119** [comment]
项目设置 本地设置 启动代码热加载可以解决
如果没有生效或者报错就重启开发者工具
![微信截图_20220219151358](https://user-images.githubusercontent.com/42491034/154791035-8835dcbc-abca-483c-bf2a-81ac8792e758.png)

**Comment by sbfkcel** [comment]
拉取最新版本的仓库，重新构建。

或者是尝试更换其它版本的微信基础库

**Comment by zx86119** [comment]
也可以考虑开发工具版本回退
亲测开发工具使用1.05.2111300版本没有问题
使用1.05.2201240就会有问题
