### ISSUE TITLE
多张图片时将img标签渲染成text标签

### ISSUE THREAD

**Issue by wangshujun1** [sbfkcel/towxml#221]
![d9c552d1492944e678065f6d933fae8](https://user-images.githubusercontent.com/48102507/154207256-ace3e8e0-4c99-493d-8001-0d41beffa324.png)
这是我appData调试里服务器传来的数据
![4517f14d962d3b6aa751662e1d0ec6f](https://user-images.githubusercontent.com/48102507/154207340-d96634ef-9861-49c4-80fb-227a448d62b9.png)
这是渲染后img标签对应的位置，变成空的text标签。
![image](https://user-images.githubusercontent.com/48102507/154207506-9514b784-3e08-41df-b6c3-117a9bf80b49.png)
js中没有对标签有特殊处理。

以前文本+一张图的模式是可以的，这次是文本中穿插三张图片，三张都显示不出来。

**Comment by sbfkcel** [comment]
将内容部分以文字的形式发一下。我周末看看

**Comment by wangshujun1** [comment]
> 

请问指哪部分内容

**Comment by sbfkcel** [comment]
解析的那部分html原始文本。

**Comment by wangshujun1** [comment]
<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>1.返岗交通补贴的对象?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴的对象是市区企业的外来员工。外来员工是指温州市户籍（含县市区）以外人员。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>2.返岗交通补贴申报途径?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴由企业通过温州产业政策兑现平台按企业参保地选择申报辖区进行申报，申报网址http://reward.wenzhou.gov.cn/app/guide/doc_read?workflow_id=1011170。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>3.返岗交通补贴的标准是多少?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>根据文件规定，补贴金额以身份证号前两位界定，补贴标准为市外省内100元/人，华东地区（上海、江苏、安徽、福建、江西、山东）300 元/人，华东以外地区 500 元/人。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>4.返岗交通补贴需要符合什么条件?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A:</strong>需要同时满足以下两个条件：</p>\r\n<section><span style=\"color: #0000ff;\">1.外来员工须参加 2022 年 1 月的企业职工养老保险或工伤保险。</span></section>\r\n<section><span style=\"color: #0000ff;\">2.在2022年2月1日至2022年2月28日返温。返温时间：乘坐公共交通回温的以目的地为温州的实名制交通票据的出发时间为准。自行返温无实名制票据的以通信大数据行程卡到达温州市显示的更新时间为准(自行回温人员应在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。)</span></section>\r\n<section></section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>5.公司返聘的已退休人员是温州市户籍以外人员，但是没有社保，是否可以申报?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>6.员工坐动车、汽车未取票，提供购票截图是否可以?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以。因购票后可以退票，无法掌握其实际是否返温，因此必须提供实名票据。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>7.员工已经取票但票据丢失，是否可以行程码代替?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>企业应当掌握员工确系外地返温的事实，并对提交的材料真实性负责，若员工确实票据丢失，可以行程码代替。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>8.员工已提供返温车票或机票等实名票据，是否还需要提供行程码?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不需要。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>9.员工自驾返温或搭车返温是否可以申报？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>可以申报。<span style=\"color: #0000ff;\">员工返温后应当在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。</span></p>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>10.行程卡要如何获取?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>员工本人通过微信或支付宝搜索&ldquo;通信行程卡&rdquo;，输入本人手机号码授权查询后可以获取行程卡（注意：员工本人名下有多个手机号码的，查询行程卡的手机号应当与申报表格所填的手机号保持一致）。也可扫码下载行程卡APP，也可在各大应用商店搜索&ldquo;通信行程卡&rdquo;下载。</span></p>\r\n<p><span style=\"color: #0000ff;\">外来员工应在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/2de3bde0d1526f988757e51b4e7bc3cf.jpg\" alt=\"\" width=\"351\" height=\"294\" /><br /></span></p>\r\n<p><strong>Q</strong>11.行程卡有什么要求?</p>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>行程卡更新的时间应当在2022年2月1日至2月28日期间，手机号码与申报填写的保持一致，行程卡显示到达的第一个地点必须是温州市且除温州市外应当有至少一个温州市以外地区。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/c109e4f295c9acb040a7c38df37a87b8.jpg\" alt=\"\" width=\"514\" height=\"766\" /><br /></span></p>\r\n</section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>12.员工在非户籍地过年返温是否符合条件?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>可以申报。例如张某是江西人，但其过年期间到其妻子父母家湖北过年，可以申报。其身份证前两位36归属江西，补贴金额按华东地区300元认定。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>13.身份证前两位与实际户籍地不一致的补贴金额如何认定?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<section><span style=\"color: #0000ff;\"><strong>A: </strong>根据规则，补贴金额以身份证前两位认定，并排除温州市户籍人员。举例：</span></section>\r\n<section><span style=\"color: #0000ff;\">1.陈某身份号前两位为36归属江西，但其已落户温州，不符合申报要求；</span></section>\r\n<section><span style=\"color: #0000ff;\">2.李某身份证3303开头归属浙江省温州市，但其户籍已落户丽水市，可以申报，补贴金额按前两位33浙江省100元给付；</span></section>\r\n<section><span style=\"color: #0000ff;\">3.赵某身份证前两位35归属福建（属华东地区），现户籍已迁往河北（属华东地区以外），其补贴金额以华东地区300给付；</span></section>\r\n<section><span style=\"color: #0000ff;\">4.张某身份证前两位为53归属云南，其已落户上海（属华东地区），但其补贴金额仍按身份证前两位云南（属华东地区以外）500元给付。</span></section>\r\n<section></section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>14.企业登陆申报系统后，提示无法申报是怎么回事?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>根据文件规定，企业留岗补贴、返岗交通补贴和&ldquo;老带新&rdquo;奖励所涉及的企业为申报时注册地和财政收入在市区范围内具有独立法人资格的企业，不含房地产企业、国有及国有控股企业、行政事业单位；&ldquo;亩均论英雄&rdquo;综合评价C、D类企业和列入严重失信名单企业不享受本政策。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>15.劳务派遣公司是否可以申报返岗交通补贴？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>劳务派遣公司申请补贴如涉及用工企业的，须告知所有用工企业，双方协商并共享相关补贴。劳务派遣企业所得补贴须做好返还实际用工企业相关记录，发放完成后一个月内提交管理部门备案。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>16.返岗交通补贴是发放给企业还是员工？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴由企业代为申报，补贴直接发放到企业员工个人银行账户。员工持有温州市民卡的，申报系统自动匹配发放到该员工市民卡银行卡内，且无法更新为其他银行卡。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>17.员工没有温州市民卡怎么办？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>员工未持有温州市民卡的，可以改填其他银行卡号。目前政府部门奖补大多发放到温州市民卡，建议员工及早办理温州市民卡。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>18.员工明细表附件有什么填写要求？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>文件规定：单位和个人对申报材料的真实准确性负责，须如实申报留温、返温和&ldquo;老 带新&rdquo;情况，配合管理部门的核查工作。返岗交通补贴由企业申报并对申报材料的真实性负责，因此公司法定代表人应当在表格内签字并加盖公司公章，并对申报材料的真实性负责。经查实提供虚假材料或劳务派遣公司不返还实际用工企业补贴的单位或个人，须如数退回已发放的补助金额，拒不配合的纳入政府部门诚信黑名单，情节严重的将追究相应法律责任。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/e484f2bfa0c05f9e91085a6e347df2e1.jpg\" alt=\"\" width=\"856\" height=\"478\" /><br /></span></p>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>19.公司法定代表人为温州市外户籍并从外地返温，是否可以申报？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以申报。</p>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n</section>

**Comment by wangshujun1** [comment]
<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>1.返岗交通补贴的对象?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴的对象是市区企业的外来员工。外来员工是指温州市户籍（含县市区）以外人员。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>2.返岗交通补贴申报途径?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴由企业通过温州产业政策兑现平台按企业参保地选择申报辖区进行申报，申报网址http://reward.wenzhou.gov.cn/app/guide/doc_read?workflow_id=1011170。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>3.返岗交通补贴的标准是多少?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>根据文件规定，补贴金额以身份证号前两位界定，补贴标准为市外省内100元/人，华东地区（上海、江苏、安徽、福建、江西、山东）300 元/人，华东以外地区 500 元/人。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>4.返岗交通补贴需要符合什么条件?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A:</strong>需要同时满足以下两个条件：</p>\r\n<section><span style=\"color: #0000ff;\">1.外来员工须参加 2022 年 1 月的企业职工养老保险或工伤保险。</span></section>\r\n<section><span style=\"color: #0000ff;\">2.在2022年2月1日至2022年2月28日返温。返温时间：乘坐公共交通回温的以目的地为温州的实名制交通票据的出发时间为准。自行返温无实名制票据的以通信大数据行程卡到达温州市显示的更新时间为准(自行回温人员应在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。)</span></section>\r\n<section></section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>5.公司返聘的已退休人员是温州市户籍以外人员，但是没有社保，是否可以申报?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>6.员工坐动车、汽车未取票，提供购票截图是否可以?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以。因购票后可以退票，无法掌握其实际是否返温，因此必须提供实名票据。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>7.员工已经取票但票据丢失，是否可以行程码代替?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>企业应当掌握员工确系外地返温的事实，并对提交的材料真实性负责，若员工确实票据丢失，可以行程码代替。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>8.员工已提供返温车票或机票等实名票据，是否还需要提供行程码?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不需要。</p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>9.员工自驾返温或搭车返温是否可以申报？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>可以申报。<span style=\"color: #0000ff;\">员工返温后应当在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。</span></p>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>10.行程卡要如何获取?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>员工本人通过微信或支付宝搜索&ldquo;通信行程卡&rdquo;，输入本人手机号码授权查询后可以获取行程卡（注意：员工本人名下有多个手机号码的，查询行程卡的手机号应当与申报表格所填的手机号保持一致）。也可扫码下载行程卡APP，也可在各大应用商店搜索&ldquo;通信行程卡&rdquo;下载。</span></p>\r\n<p><span style=\"color: #0000ff;\">外来员工应在回温且行程卡信息更新后第一时间提供通信大数据行程卡截图交企业备案保存。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/2de3bde0d1526f988757e51b4e7bc3cf.jpg\" alt=\"\" width=\"351\" height=\"294\" /><br /></span></p>\r\n<p><strong>Q</strong>11.行程卡有什么要求?</p>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>行程卡更新的时间应当在2022年2月1日至2月28日期间，手机号码与申报填写的保持一致，行程卡显示到达的第一个地点必须是温州市且除温州市外应当有至少一个温州市以外地区。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/c109e4f295c9acb040a7c38df37a87b8.jpg\" alt=\"\" width=\"514\" height=\"766\" /><br /></span></p>\r\n</section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>12.员工在非户籍地过年返温是否符合条件?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>可以申报。例如张某是江西人，但其过年期间到其妻子父母家湖北过年，可以申报。其身份证前两位36归属江西，补贴金额按华东地区300元认定。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>13.身份证前两位与实际户籍地不一致的补贴金额如何认定?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<section><span style=\"color: #0000ff;\"><strong>A: </strong>根据规则，补贴金额以身份证前两位认定，并排除温州市户籍人员。举例：</span></section>\r\n<section><span style=\"color: #0000ff;\">1.陈某身份号前两位为36归属江西，但其已落户温州，不符合申报要求；</span></section>\r\n<section><span style=\"color: #0000ff;\">2.李某身份证3303开头归属浙江省温州市，但其户籍已落户丽水市，可以申报，补贴金额按前两位33浙江省100元给付；</span></section>\r\n<section><span style=\"color: #0000ff;\">3.赵某身份证前两位35归属福建（属华东地区），现户籍已迁往河北（属华东地区以外），其补贴金额以华东地区300给付；</span></section>\r\n<section><span style=\"color: #0000ff;\">4.张某身份证前两位为53归属云南，其已落户上海（属华东地区），但其补贴金额仍按身份证前两位云南（属华东地区以外）500元给付。</span></section>\r\n<section></section>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>14.企业登陆申报系统后，提示无法申报是怎么回事?</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>根据文件规定，企业留岗补贴、返岗交通补贴和&ldquo;老带新&rdquo;奖励所涉及的企业为申报时注册地和财政收入在市区范围内具有独立法人资格的企业，不含房地产企业、国有及国有控股企业、行政事业单位；&ldquo;亩均论英雄&rdquo;综合评价C、D类企业和列入严重失信名单企业不享受本政策。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>15.劳务派遣公司是否可以申报返岗交通补贴？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>劳务派遣公司申请补贴如涉及用工企业的，须告知所有用工企业，双方协商并共享相关补贴。劳务派遣企业所得补贴须做好返还实际用工企业相关记录，发放完成后一个月内提交管理部门备案。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>16.返岗交通补贴是发放给企业还是员工？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>返岗交通补贴由企业代为申报，补贴直接发放到企业员工个人银行账户。员工持有温州市民卡的，申报系统自动匹配发放到该员工市民卡银行卡内，且无法更新为其他银行卡。</span></p>\r\n</section>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>17.员工没有温州市民卡怎么办？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>员工未持有温州市民卡的，可以改填其他银行卡号。目前政府部门奖补大多发放到温州市民卡，建议员工及早办理温州市民卡。</span></p>\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>18.员工明细表附件有什么填写要求？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><span style=\"color: #0000ff;\"><strong>A: </strong>文件规定：单位和个人对申报材料的真实准确性负责，须如实申报留温、返温和&ldquo;老 带新&rdquo;情况，配合管理部门的核查工作。返岗交通补贴由企业申报并对申报材料的真实性负责，因此公司法定代表人应当在表格内签字并加盖公司公章，并对申报材料的真实性负责。经查实提供虚假材料或劳务派遣公司不返还实际用工企业补贴的单位或个人，须如数退回已发放的补助金额，拒不配合的纳入政府部门诚信黑名单，情节严重的将追究相应法律责任。</span></p>\r\n<p><span style=\"color: #0000ff;\"><img src=\"/uploads/20220215/e484f2bfa0c05f9e91085a6e347df2e1.jpg\" alt=\"\" width=\"856\" height=\"478\" /><br /></span></p>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<section>\r\n<section>\r\n<section data-brushtype=\"text\"><strong>Q</strong>19.公司法定代表人为温州市外户籍并从外地返温，是否可以申报？</section>\r\n</section>\r\n</section>\r\n<section data-autoskip=\"1\">\r\n<p><strong>A: </strong>不可以申报。</p>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n</section>\r\n</section>

**Comment by wangshujun1** [comment]
[新建文本文档 (2).txt](https://github.com/sbfkcel/towxml/files/8077324/2.txt)

**Comment by wangshujun1** [comment]
[新建 Microsoft Word 文档.docx](https://github.com/sbfkcel/towxml/files/8077365/Microsoft.Word.docx)

**Comment by wangshujun1** [comment]
问题解决了，img标签前多了个上面设置字体样式的<span>标签，导致解析成了text标签，删除后图片正常显示。

<p>**<span style=\"color: #0000ff;\">**<img src=\"/uploads/20220215/e484f2bfa0c05f9e91085a6e347df2e1.jpg\" alt=\"\" width=\"856\" height=\"478\" /><br /></span>
