### ISSUE TITLE
渲染出的图片如何居中？

### ISSUE THREAD

**Issue by vinnyzhaowenyu** [sbfkcel/towxml#229]
使用 towxml 渲染 Markdown 的图片可以正常渲染出来，但是当屏幕比图片大很多时图片居左侧布局不符合我们的预期

尝试了使用 `<center></center>` 标签直接跳过解析

请问还有其他方法让图片剧中吗？

**Comment by sbfkcel** [comment]
尝试一下添加行间样式呢。

**Comment by vinnyzhaowenyu** [comment]
需要怎么添加呢？不是太清楚，帮忙指导一下

**Comment by sbfkcel** [comment]
<div style="text-align:center;"><img src=""/></div>

**Comment by vinnyzhaowenyu** [comment]
好的，我试下，非常感谢

**Comment by vinnyzhaowenyu** [comment]
> ```
> <div style="text-align:center;"><img src=""/></div>
> ```

这种方式是可以让图片居中的，非常感谢。

但是这种写法完全是 HTML 的语法了，Markdown 的解析时也可以评估支持类似功能。

比如 CSDN 的 Markdown 解析支持 `#pic_center` 标签让图片居中显示

**Comment by sbfkcel** [comment]
> > ```
> > <div style="text-align:center;"><img src=""/></div>
> > ```
> 
> 这种方式是可以让图片居中的，非常感谢。
> 
> 但是这种写法完全是 HTML 的语法了，Markdown 的解析时也可以评估支持类似功能。
> 
> 比如 CSDN 的 Markdown 解析支持 `#pic_center` 标签让图片居中显示

默认都是左对齐，你可以考虑修改towxml样式。全局将图片设置为居中

**Comment by vinnyzhaowenyu** [comment]
找了一个思路

通过在 `towxml/img/img.wxml` 中添加一层 view 来控制图片居中，markdown 中就不需要特殊编辑 HTML 了

```
<view style="text-align: center;"><image class="{{attrs.class}}" lazy-load="true" mode="{{attrs.mode || 'widthFix'}}" src="{{attrs.src}}" style="{{attrs.style}} width:{{size.w}}px;height:{{size.h}}px;" bindload="load"></image></view>
```
