### ISSUE TITLE
请问这个支持分隔线吗？我试了不行，谢谢

### ISSUE THREAD

**Issue by zhang177177** [sbfkcel/towxml#23]
请问这个支持分隔线吗？我试了不行，谢谢

**Comment by sbfkcel** [comment]
给具体的代码内容。

**Comment by zhang177177** [comment]
分隔线
你可以在一行中用三个以上的星号、减号、底线来建立一个分隔线，行内不能有其他东西。你也可以在星号或是减号中间插入空格。下面每种写法都可以建立分隔线：

* * *

***

*****

- - -

---------------------------------------p
就是这个不支持

**Comment by zhang177177** [comment]
直接用你们的demo解析三个星号或者三个头号,没有出现分隔线

**Comment by zhang177177** [comment]
好像用你们有demo可以

**Comment by sbfkcel** [comment]
不客气
