### ISSUE TITLE
链接类型会自动换行

### ISSUE THREAD

**Issue by z1485671578** [sbfkcel/towxml#237]
带有链接的情况下，链接会单独占满一行
![image](https://user-images.githubusercontent.com/58332474/190987251-0c0e13a6-9796-49a9-bece-19ce6adff4d3.jpeg)![image](https://user-images.githubusercontent.com/58332474/190987281-9d622613-a9f7-4413-a514-38fd84569eec.jpeg)

**Comment by z1485671578** [comment]
DIYgod是个链接

**Comment by sbfkcel** [comment]
更新，已经处理
