### ISSUE TITLE
小程序云函数解析有问题

### ISSUE THREAD

**Issue by fvaryu** [sbfkcel/towxml#239]
内容是这样的，在vscode下编辑及显示如下
![image](https://user-images.githubusercontent.com/6380335/192672171-b0a8afae-9e69-49be-b846-b70c5c2d9c38.png)

小程序显示效果如下：
![image](https://user-images.githubusercontent.com/6380335/192672246-820b6799-b692-4cea-ba57-37315c38a0f7.png)

小程序云函数调用后返回的内容，好像是把换行去掉了
![image](https://user-images.githubusercontent.com/6380335/192672579-add49963-1647-45e3-a774-270312e8cf3a.png)

小程序开发菜鸟，不知道哪里有问题，还望指正

**Comment by fvaryu** [comment]
原因不知道：临时解决方法是原始文本换行用&hc结尾，拿到数据后把&hc替换成\n解析就正确了

**Comment by sbfkcel** [comment]
检查你服务器上的编码。换行都是 `\r|\n` 怎么会是 &hc ?

**Comment by fvaryu** [comment]
我没服务器，用他是腾讯云函数 云存储，我不清楚哪里有问题， \r\n 无效， 我使用&hc作为特殊标记，然后小程序本地再把&hc替换为\n, 才能正常换行，云函数返回来的\n不能换行

**Comment by fvaryu** [comment]
关闭吧，这个库没关系， 跟小程序有关，具体啥关系搞不清，刚学小程序
