### ISSUE TITLE
towxml.vvadd.com响应时间过长

### ISSUE THREAD

**Issue by I-want-to-fly-higher** [sbfkcel/towxml#246]
最近解析公式一直显示[渲染层网络层错误] Failed to load image，然后点击图片url，一直显示显示响应时间过长，这个是服务器的问题吗

**Comment by sbfkcel** [comment]
那个是演示服务器，欠费停掉了。

**Comment by I-want-to-fly-higher** [comment]
这能换成自己的服务器吗，有偿的

**Comment by sbfkcel** [comment]
可以的，根据WIKI教程来就行了。

**Comment by I-want-to-fly-higher** [comment]
不知道这个wiki-_-

**Comment by sbfkcel** [comment]
https://github.com/sbfkcel/towxml/wiki
