### ISSUE TITLE
不能解析 markdown 中的 todolist

### ISSUE THREAD

**Issue by JQiue** [sbfkcel/towxml#247]
![image](https://user-images.githubusercontent.com/45145407/218309235-ffca7502-2bf8-4036-ae3b-fe13d5425efb.png)

**Comment by JQiue** [comment]
上下标也是不支持的

![image](https://user-images.githubusercontent.com/45145407/218311491-75554bc8-c933-4a29-ad83-6d4e0d2e9a68.png)

**Comment by sbfkcel** [comment]
看wiki中的demo

**Comment by JQiue** [comment]
很显而易见的是，demo 也是这样，这和构建的 towxml 产物有关系

**Comment by JQiue** [comment]
当将`config.js`中的`highlight`全部禁用就会产生这种情况

**Comment by sbfkcel** [comment]
处理了，重新拉取一下。
