### ISSUE TITLE
小程序 在分包里页面onload 生命周期中异步加载towxml 模块， 提示"module 'towxml/languages/c-like.js' is not defined，请问问题出在哪里

### ISSUE THREAD

**Issue by auroav** [sbfkcel/towxml#248]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/97878734/220272395-2e091616-8b71-4873-b1c5-79af615c132f.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/97878734/220272494-d5464d34-4441-47b6-9b3a-df5d2286ccc3.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/97878734/220272562-f3c019b4-0ce9-41e5-bfdd-ef1cfc4b0df2.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/97878734/220272884-291cd35c-3f71-40f2-8617-99ab0c131c98.png">

**Comment by sbfkcel** [comment]
分包towxml相关文件归为一个试试

**Comment by auroav** [comment]
感谢，找到问题了，页面中towxml组件没有挂载，还是使用的占位组件
