### ISSUE TITLE
公式中的{\partial的\会被忽略，导致服务器公式生成错误

### ISSUE THREAD

**Issue by 94dreamer** [sbfkcel/towxml#251]
app.towxml('$\frac{\partial x}{\partial x}$ 和 $\frac{\partial x}{\partial y}$', 'markdown')

发起的请求为 https://xxx.com?tex=%0Crac%7Bpartial%20x%7D%7Bpartial%20x%7D&theme=light

![image](https://user-images.githubusercontent.com/15634204/236220888-bd77b407-6955-44c8-a02b-76c9b966359d.png)

![image](https://user-images.githubusercontent.com/15634204/236221040-1c190558-72f0-4954-ae9d-4955669d0cea.png)

**Comment by sbfkcel** [comment]
转译，多加一条斜杠
