### ISSUE TITLE
markdown 公式无法解析

### ISSUE THREAD

**Issue by INTKILOW** [sbfkcel/towxml#253]
首先计算出 $7m^2-14m = 7(1+\sqrt{2})^2 - 14(1+\sqrt{2}) = -7\sqrt{2}$，$3n^2-6n-7 = 3(1-\sqrt{2})^2-6(1-\sqrt{2})-7 = -7\sqrt{2}$。因此 $(7m^2-14m+a)(3n^2-6n-7) = (-7\sqrt{2}+a)(-7\sqrt{2})=8$。解得 $a = \frac{8}{7\sqrt{2}}-7\sqrt{2} = -\frac{37}{7}\sqrt{2}$。所以 $a=-\frac{37}{7}\sqrt{2}$。

**Comment by INTKILOW** [comment]
`首先计算出 $7m^2-14m = 7(1+\sqrt{2})^2 - 14(1+\sqrt{2}) = -7\sqrt{2}$，$3n^2-6n-7 = 3(1-\sqrt{2})^2-6(1-\sqrt{2})-7 = -7\sqrt{2}$。因此 $(7m^2-14m+a)(3n^2-6n-7) = (-7\sqrt{2}+a)(-7\sqrt{2})=8$。解得 $a = \frac{8}{7\sqrt{2}}-7\sqrt{2} = -\frac{37}{7}\sqrt{2}$。所以 $a=-\frac{37}{7}\sqrt{2}$。`

**Comment by INTKILOW** [comment]
![image](https://github.com/sbfkcel/towxml/assets/20120514/6401e25e-705c-46f7-8b8d-27215c4aca50)

**Comment by INTKILOW** [comment]
样式怎么调整

**Comment by sbfkcel** [comment]
这种复杂的公式，建议使用块公式。否则你怎么调都显示不下
