### ISSUE TITLE
渲染卡顿问题

### ISSUE THREAD

**Issue by xgykx** [sbfkcel/towxml#263]
目前是有一个需要切换的需求,切换卡片,拿到新的数据重新渲染页面,但是重新渲染时,页面会很卡,有没有什么办法能够优化

**Comment by xgykx** [comment]
重新渲染就是更换数据重新渲染markdown格式数据

**Comment by sbfkcel** [comment]
录一个 视频或动图？

**Comment by xgykx** [comment]
抱歉,现在好像又不卡了,不知道为什么 😂

**Comment by xgykx** [comment]
另外,问一下,这个可以商业吗?

**Comment by xgykx** [comment]
另外,问一下,这个可以商用吗?
