### ISSUE TITLE
md中的换行“  ”解析有问题

### ISSUE THREAD

**Issue by pepperdog999** [sbfkcel/towxml#27]
使用md中标准的换行"  "会有问题。如下：
第1行    
第2行  
第3行

解析出来为：
<viewclass="h2w__p"id="">
第1行
<viewclass="h2w__br"id=""></view>
</view>
第2行
<viewclass="h2w__br"id=""></view>
第3行

这样就会在第1行下面空一大段(h2w__p的样式)，请问该如何解决？

**Comment by sbfkcel** [comment]
这解析是正常的啊。

**Comment by pepperdog999** [comment]
我改了一下排版，明显有问题哦。第一行和下面行中间会有很大一个间隔。
