### ISSUE TITLE
latex 公式在微信开发者工具能解析，到了真机就不行了。

### ISSUE THREAD

**Issue by bawbeans** [sbfkcel/towxml#271]
微信开发者中
<img width="406" alt="image" src="https://github.com/sbfkcel/towxml/assets/16595811/f8b938a3-eefb-4dc9-9465-cce1eff856cb">

真机中
<img width="391" alt="image" src="https://github.com/sbfkcel/towxml/assets/16595811/db7a86fc-4aaa-4adf-92de-dad8eb20426a">

有大佬知道这个问题么？

**Comment by sbfkcel** [comment]
白名单
