### ISSUE TITLE
渲染latex公式，必须后端必须是node环境吗，unicloud或者其他后端环境可以吗

### ISSUE THREAD

**Issue by drucker2310** [sbfkcel/towxml#274]

**Comment by sbfkcel** [comment]
不需要后端也可以，那个是商业版本。现阶段无法公开。

**Comment by drucker2310** [comment]
商业版本贵不贵，怎么个收费方式

---- 回复的原邮件 ----
| 发件人 | Fried ***@***.***> |
| 发送日期 | 2023年11月21日 21:32 |
| 收件人 | sbfkcel/towxml ***@***.***> |
| 抄送人 | drucker2310 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [sbfkcel/towxml] 渲染latex公式，必须后端必须是node环境吗，unicloud或者其他后端环境可以吗 (Issue #274) |

不需要后端也可以，那个是商业版本。现阶段无法公开。

**Comment by sbfkcel** [comment]
单个个体一次性授权。如果是个人建议搭个服务器就行，没必要购买

**Comment by drucker2310** [comment]
好的，谢谢你。我是个刚自学几个月的个体开发者，这个后端是必须node环境服务器吗，还是只要是个服务器都行呢

---- 回复的原邮件 ----
| 发件人 | Fried ***@***.***> |
| 发送日期 | 2023年11月22日 08:56 |
| 收件人 | sbfkcel/towxml ***@***.***> |
| 抄送人 | drucker2310 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [sbfkcel/towxml] 渲染latex公式，必须后端必须是node环境吗，unicloud或者其他后端环境可以吗 (Issue #274) |

单个个体一次性授权。如果是个人建议搭个服务器就行，没必要购买

**Comment by sbfkcel** [comment]
自学或个人自己根据WIKI教程来搭吧。如果是企业或商业项目建议购买，还能节省成本。
