### ISSUE TITLE
数学公式无法渲染，链接好像无法访问

### ISSUE THREAD

**Issue by Versus2017** [sbfkcel/towxml#276]
towxml.vvadd.com  需要确认是否仍然可用：
公式：```$x = {-b pm sqrt{b^2-4ac} over 2a}.$```
我的组件渲染出来了，但是图片没显示：
<img width="461" alt="image" src="https://github.com/sbfkcel/towxml/assets/15376226/32dcee3b-b787-4652-9c30-a504d79fbf03">

**Comment by sbfkcel** [comment]
我个人服务器欠费了，需要自己参考WIKI搭建公式服务器。或购买纯前台解析支持。
