### ISSUE TITLE
微信小程序解析latex,解析不完整,而且不换行

### ISSUE THREAD

**Issue by 15203284409** [sbfkcel/towxml#283]
![image](https://github.com/sbfkcel/towxml/assets/71250336/48bfce9d-26d3-4334-b7d8-c7e6b59a85ac)
![image](https://github.com/sbfkcel/towxml/assets/71250336/ffd9b916-8f84-4c9a-903a-1cbc0d825404)
![image](https://github.com/sbfkcel/towxml/assets/71250336/f9d1d525-c131-4aae-9dda-8934c3e7ed85)

**Comment by sbfkcel** [comment]
注意转换，看DEMO和其它issues
