### ISSUE TITLE
npm 安装 后的路径问题

### ISSUE THREAD

**Issue by taitanxiami** [sbfkcel/towxml#29]
Error:
in File ./pages/detail.wxss

File not found: /towxml/style/main.wxss
编译.wxss 文件错误，错误信息如上，可在控制台查看详情信息
 
样式中这么写的：
/**引入主题样式**/
  @import '../towxml/style/main.wxss';
  @import '/towxml/style/theme/light.wxss';
  @import '/towxml/style/theme/dark.wxss';

**Comment by sbfkcel** [comment]
直接克隆使用吧。
