### ISSUE TITLE
Markdown解析图片时 towxml 方法进入死循环

### ISSUE THREAD

**Issue by onechunlin** [sbfkcel/towxml#290]
## 背景
流式输出 markdown 文本，实时渲染

## 问题
当遇到图片前缀没正确闭合时，会进入死循环。最小复现示例
```js
const nodes = towxml(`![北`, 'markdown')
```

## 预期
不进入死循环，未正确闭合时兜底展示纯文本

**Comment by sbfkcel** [comment]
经过测试，问题不存在。

**Comment by sbfkcel** [comment]
![image](https://github.com/user-attachments/assets/4a6e20c5-dc13-4f4c-9c6c-3368fa2cf53e)

**Comment by onechunlin** [comment]
确实，是内部基于 taro 封装的库在使用循环里使用的问题，感谢~
