### ISSUE TITLE
请问下videa都支持什么视频格式，或者链接，另外如果解决层级覆盖问题，video一直在最上面，谢谢

### ISSUE THREAD

**Issue by zhang177177** [sbfkcel/towxml#30]
请问下video都支持什么视频格式，或者链接，另外如果解决层级覆盖问题，video一直在最上面，谢谢

**Comment by sbfkcel** [comment]
mp4或webm应该都是支持的。层覆盖的问题好像是没办法解决。

**Comment by zhang177177** [comment]
我试了下,可以支持开眼视频链接,请教下能不能支持优酷,或者爱奇艺,腾讯视频链接,或者抖音,谢谢

**Comment by sbfkcel** [comment]
你能找到视频源地址应该是可以的，至少腾讯肯定是可以的。
