### ISSUE TITLE
关于连续解析md时，项目序号后产生换行的问题

### ISSUE THREAD

**Issue by Mageenz** [sbfkcel/towxml#300]
真机（iphone13）上有这个问题，开发者工具上ok。

问题表现：连续解析md时，1、2、3等项目序号后面会产生换行，以下是图片：
![8dad4d81fd3df35e8afa92839d28397](https://github.com/user-attachments/assets/747b3a55-20f7-46f6-a8c5-615b24c00ed2)

我检查过原内容，序号后确实是没有换行的，但是解析后就变成这样了，还有很奇怪的一点是，一次性解析就没问题，只有连续解析时才发生这个问题。

**Comment by Mageenz** [comment]
这应该是微信的问题，现在通过每次解析后用key重置节点的方式解决了这个问题

**Comment by ovo-zhou** [comment]
是渲染list的时候，每次都给一个新key吗

**Comment by DGLH** [comment]
能详细说一下怎么改的吗
