### ISSUE TITLE
数学公式解析错误

### ISSUE THREAD

**Issue by TLovers** [sbfkcel/towxml#305]
```ts
app.towxml(`[a^3 - b^3 = (a - b)(a^2 + ab + b^2)]`, 'markdown', {
                theme: this.data.theme,
                events: {
                    tap: (event: WechatMiniprogram.CustomEvent) => {
                        console.log('tap event', event)
                    },
                    change: (event: WechatMiniprogram.CustomEvent) => {
                        console.log('todo chnage event', event)
                    },
             a },
 })
```
上面代码无法正确渲染出latex，想了解下如何定位这个问题，通过debugger发现md(str) 并没有返回类似`<latex>` 这样的标签，我找不知道如何定位这个问题，是markdown.js 的问题还是什么

**Comment by hanxuallan** [comment]
我也想知道如何实现数学公式解析的具体步骤以及方案，好像是有纯前端的方法。

**Comment by sbfkcel** [comment]
[看演示和文档呀](https://github.com/sbfkcel/towxml/wiki/3.0-%E6%95%B0%E5%AD%97%E5%85%AC%E5%BC%8F&yuml%E6%B5%81%E7%A8%8B%E5%9B%BE%E6%94%AF%E6%8C%81)

**Comment by TLovers** [comment]
> [看演示和文档呀](https://github.com/sbfkcel/towxml/wiki/3.0-%E6%95%B0%E5%AD%97%E5%85%AC%E5%BC%8F&yuml%E6%B5%81%E7%A8%8B%E5%9B%BE%E6%94%AF%E6%8C%81)

已经来来回回把这个说明看了不下10遍了。比如这个`[a^3 - b^3 = (a - b)(a^2 + ab + b^2)] `  直接用这个文案去请求node服务是能正确解析的，但是md（`[a^3 - b^3 = (a - b)(a^2 + ab + b^2)] `） 去解析的时候将其解析成了text，也就是虚拟dom的tag并不是latex，这样在渲染的时候并不是以`latex`标签的形式去渲染，我想找到这个字符为什么没有正确解析成latex.可是现在卡在这里了，想问下作者大佬，是不是markdown.js 的render方法那里出问题了

**Comment by sbfkcel** [comment]
公式的语法要求是 `$` 符号开始中和结束的。

如果是块公司则是三个 `$$$` 符号

**Comment by TLovers** [comment]
> 公式的语法要求是 `$` 符号开始中和结束的。
> 
> 如果是块公司则是三个 `$$$` 符号

你的意思是想要md（str）解析出正确的nodes，这里的str就必须`$[a^3 - b^3 = (a - b)(a^2 + ab + b^2)]$ `这样？
因为我尝试直接用[a^3 - b^3 = (a - b)(a^2 + ab + b^2)]去请求服务器是能正确返回svg的比如`（xxxx.com/towxml/?tex=[a^3%20-%20b^3%20=%20(a%20-%20b)(a^2%20+%20ab%20+%20b^2)]`会返回一个svg

**Comment by TLovers** [comment]
> 公式的语法要求是 `$` 符号开始中和结束的。
> 
> 如果是块公司则是三个 `$$$` 符号
> 
> 从你提供的演示代码中只是公式字符串而已。

想追问一个问题，这种$的规则，如果我想去定制化，是修改那块的代码呢？是需要去就改markdown.js的解析规则吗？麻烦能指下方向吗

**Comment by sbfkcel** [comment]
这是markdown语言标准。你要修改那就去修改源码中的 markdown 解析器那部分了。

**Comment by chenqiuling** [comment]
通常markdown规则里公式格式为：
`$公式表达式$` 或 `$$公式表达式$$`，你在vscode里创建一个markdown文件预览就能看到。
但是有的情况下，比如我是处理的某ai大模型返回的markdown格式，它返回的公式格式是 `(公式表达式)` 或 `[公式表达式]` ，开始结束符合与这个库里的符号不一致。

我是通过正则匹配转换解决的这个问题。
```
str.replace(/\\\(\s*(.*?)\s*\\\)/g, "$$$1$$") // 行公式规则转换
    .replace(/\\\[\s*(.*?)\s*\\\]/g, "$$$$$1$$$$") // 块公式规则转换
```
@TLovers

**Comment by TLovers** [comment]
> 通常markdown规则里公式格式为： `$公式表达式$` 或 `$$公式表达式$$`，你在vscode里创建一个markdown文件预览就能看到。 但是有的情况下，比如我是处理的某ai大模型返回的markdown格式，它返回的公式格式是 `(公式表达式)` 或 `[公式表达式]` ，开始结束符号与这个库里的符号不一致。
> 
> 我是通过正则匹配转换解决的这个问题。
> 
> ```
> str.replace(/\\\(\s*(.*?)\s*\\\)/g, "$$$1$$") // 行公式规则转换
>     .replace(/\\\[\s*(.*?)\s*\\\]/g, "$$$$$1$$$$") // 块公式规则转换
> ```
> 
> 如果想通过改源码方式处理，对应的源码位置在 towxml/parse/markdown/plugins/latex.js 会涉及到转义字符(\(、\)、\[、\])，还需要改移动的步数等等。
> 
> @TLovers

谢谢你，我试试
