### ISSUE TITLE
MD转为html中有<br />标签时，会有闭包判断错误。

### ISSUE THREAD

**Issue by pepperdog999** [sbfkcel/towxml#32]
MD转为html中有<br />标签时，比如MD的换行符，最后的渲染会变成<view class="h2w__br" /></view>。这会在显示上造成一些问题，请问怎么修正？

**Comment by pepperdog999** [comment]
MD内容：
第1行  
第2行  
第3行  

每一行后有两个空格，解析出来的HTML内容：
<view class="h2w__p">第1行<view class="h2w__br" /></view>
第2行<view class="h2w__br" /></view>
第3行</view>

**Comment by sbfkcel** [comment]
我抽空看一下。

**Comment by sbfkcel** [comment]
![snipaste_2018-08-03_20-30-59](https://user-images.githubusercontent.com/5469785/43642978-2870b664-975c-11e8-85ca-16a323fde5ee.png)
重现不了你的问题。
