### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by Sing1** [sbfkcel/towxml#33]
加载md文件显示白屏，如果打开调试模式就好了，关掉就是白屏

**Comment by sbfkcel** [comment]
真机上面吗？

**Comment by Sing1** [comment]
好像是我的问题


发自我的 iPhone

**Comment by Sing1** [comment]
不能加载md片段吗

**Comment by sbfkcel** [comment]
可以的，你发一下具体代码。

**Comment by Sing1** [comment]
是我配置的问题，你的代码没什么问题，可以删除或者关闭了...

**Comment by sbfkcel** [comment]
感谢讨论。

**Comment by Sing1** [comment]
又发现了一个问题，我不是直接加在的文件，而是加载的md格式的文字，但是达到一定长度后后面的不显示了


发自我的 iPhone
