### ISSUE TITLE
解析background-color样式问题

### ISSUE THREAD

**Issue by AlienC** [sbfkcel/towxml#35]
### 接口返回的数据：
`<p><span style="background-color: rgb(255, 0, 0);">合理的膳食构成，科学而营养的搭配 ，是维持人体健康的重要方面。</span></p>`

### 插件转换后：
`<text class="h2w__span"id=""style="background-color:,rgb(255,,0,,0);">合理的膳食构成，科学而营养的搭配 ，是维持人体健康的重要方面。</text>`

> 发现background-color后面多了几个小逗号，color也有这样的问题，导致背景颜色和字体颜色不显示。

**Comment by sbfkcel** [comment]
预计下个大版本修复。先用`red`或`#ff0000`代替一下。

**Comment by sbfkcel** [comment]
尝试下使用`next`分支的代码版本，已经修复该问题。
