### ISSUE TITLE
iframe 标签解析不了吗？

### ISSUE THREAD

**Issue by pangrongxian** [sbfkcel/towxml#38]
下面这一段代码，直接放在MD文件中是可以播放的视频，在MD工具中可以播放，但是到了小程序里面解析不出来耶。。

<iframe src="http://www.skyfollowsnow.pro/?url=http://www.iqiyi.com/v_19rro8i0g4.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>

**Comment by sbfkcel** [comment]
抱歉，iframe是不支持的。需要支持视频请使用video标签。

**Comment by pangrongxian** [comment]
是暂时不支持，还是这个很难做到呢？

**Comment by sbfkcel** [comment]
很难做到。
