### ISSUE TITLE
wepy demo

### ISSUE THREAD

**Issue by sbfkcel** [sbfkcel/towxml#40]
wepy框架应用demo

使用方法：
- 解压
- 安装依赖`cnpm install`
- 将解压目录添加到小程度开发工具中
- wepy build --watch

[wepy demo.zip](https://github.com/sbfkcel/towxml/files/2363011/wepy.demo.zip)

**Comment by vudiy** [comment]
请问这个你怎么解决的？？

**Comment by sbfkcel** [comment]
这就是一个示例demo，正常使用。

**Comment by qianlanse** [comment]
@sbfkcel 这个是打包出的错，我今天也遇到了，不知道是那里问题
