### ISSUE TITLE
渲染真的是特别慢

### ISSUE THREAD

**Issue by bimohxh** [sbfkcel/towxml#41]
对比了一下 wxparse， 发现您的这个很慢，应该是慢在渲染上了，不知道你做了什么操作，然后mardown的代码块横向滑动也有问题，特别长

**Comment by sbfkcel** [comment]
慢是在哪引阶段？

**Comment by bimohxh** [comment]
我测试了一下，转换数据好像是200毫秒左右吧，预测是渲染慢了，到时我把转换放到服务器上面再试试。那个template 文件太大了，我删了很多，其实我就是需要一个常规markdown的解析而已，但是里面还有swiper什么的，体积太大。还有一些高亮的文件，不用的我都删掉了。


那个代码横向滚动我试了，确实如你所说，这样体验会更好一点。

**Comment by sbfkcel** [comment]
嗯。由于照顾到一些用户反馈在使用html5标签时，与wxml重复的标签不能被直接较好的直接转换。所以这里有照顾到在html中渲染原生wxml标签的情况。
不需要的代码可以通过修改`outTemplate.js`第30行，删除对应的标签。
在`outTemplate.js`最后一行修改解析层级`depth:10`，值越小文件也越小。
删除`outTemplate.js`中的`68-79行`，剔除事件绑定功能也能有效减少文件大小。
最后运行`node outTemplate.js`会生成新的`renderTemplate.wxml`文件。

**Comment by bimohxh** [comment]
谢谢！

**Comment by JaimeCheng** [comment]
我想问一下 为什么 renderTemplate 要重复那么多遍呢 ？求解答

**Comment by sbfkcel** [comment]
> 我想问一下 为什么 renderTemplate 要重复那么多遍呢 ？求解答

小程序旧版本不支持模版互相嵌套调用。近期会发布新版本，采用其它方式实现。同时也会新增加很多功能。

**Comment by JaimeCheng** [comment]
> > 我想问一下 为什么 renderTemplate 要重复那么多遍呢 ？求解答
> 
> 小程序旧版本不支持模版互相嵌套调用。近期会发布新版本，采用其它方式实现。同时也会新增加很多功能。

非常期待新版 感谢作者
