### ISSUE TITLE
在wepy框架的demo中build出现错误。

### ISSUE THREAD

**Issue by Shing952** [sbfkcel/towxml#42]
![image](https://user-images.githubusercontent.com/23016067/45469729-46a72200-b75d-11e8-9d04-af5d0dd360c4.png)

**Comment by sbfkcel** [comment]
参见：

**Comment by qianlanse** [comment]
@sbfkcel 这个是打包出的错，我今天也遇到了跟上面一样，不知道是那里问题

**Comment by qianlanse** [comment]
@Shing952 请问你最后是怎么解决的呢
