### ISSUE TITLE
真机环境 图片显示问题

### ISSUE THREAD

**Issue by jacky8466** [sbfkcel/towxml#44]
使用微信工具调试图片可以正常显示，但真机调试，或者预览不显示：
微信工具显示的代码：
 Object]"id=""mode="widthFix"src="XXX/10.gif"style="height: 361px;"></image>
是有style 属性的，但真机调试，或者预览情况下，发现代码是这样的：
Object]"id=""mode="widthFix"src="XXX//10.gif"></image>
没有style属性，我怀疑的是因为没有高度才不显示的，我不确定是不是插件的BUG还是微信的BUG

**Comment by sbfkcel** [comment]
周末，抽时间看一下。是IOS还是android？

**Comment by sbfkcel** [comment]
想了一下是故意这么设置的。
mode为`widthFix `会按图片宽度自行进行等比例拉伸。
因为在大多数情况下，移动端的图片都是100%宽显示会比较友好。

如果确实需要自行设置图片大小，打开outTemplates.js  

找到以下代码进行删除：
```javascript
if(item === 'image'){
    imgMode = `mode="{{item.type === 'audio' ? '' : 'widthFix'}}"`;
};
```

之后运行 `node outTemplate.js`生成新的渲染模版文件即可。

**Comment by hellobugme** [comment]
> 想了一下是故意这么设置的。
> mode为`widthFix `会按图片宽度自行进行等比例拉伸。
> 因为在大多数情况下，移动端的图片都是100%宽显示会比较友好。
> 
> 如果确实需要自行设置图片大小，打开outTemplates.js
> 
> 找到以下代码进行删除：
> 
> ```js
> if(item === 'image'){
>     imgMode = `mode="{{item.type === 'audio' ? '' : 'widthFix'}}"`;
> };
> ```
> 
> 之后运行 `node outTemplate.js`生成新的渲染模版文件即可。

`if(item === 'image'){
     imgMode = `mode="{{item.type === 'audio' ? '' : (item.attr&&item.attr.mode || 'widthFix')}}"`;
};`
这样改就行了，如果html里自己已经给mode赋值了，就用赋值的，没有再用默认值 widthFix

**Comment by sbfkcel** [comment]
也是可以的。自己动手，丰衣足食。
