### ISSUE TITLE
没办法运行

### ISSUE THREAD

**Issue by TimLiu1** [sbfkcel/towxml#46]
![image](https://user-images.githubusercontent.com/16770736/48241657-d04c3680-e412-11e8-9020-517bb975794e.png)
下载下来运行就出错 node  version 10 and 8

**Comment by sbfkcel** [comment]
少了参数

**Comment by TimLiu1** [comment]
> 少了参数
> 
> ```
> res.data,               // `markdown`或`html`文本内容
> 'markdown',         // `markdown`或`html`
>  this                      // 当前页面的`this`（2.1.0或以上的版本该参数不可省略）
> ```

我是copy官方文档

**Comment by sbfkcel** [comment]
哦，想起来了。新版本貌似没去考虑到这个问题。 稍后我发一下新版本。

**Comment by sbfkcel** [comment]
在服务器端生成数据可以使用`2.0.2`版本。新版本由于对audio作了解析，需要在前台作一些操作。具体的兼容办法需要抽些时间再处理。

**Comment by sbfkcel** [comment]
最新版本已经支持。
