### ISSUE TITLE
事件绑定失败

### ISSUE THREAD

**Issue by jackkam85** [sbfkcel/towxml#48]
Cannot set property 'event_bind_tap' of undefined;at App loading function;at api request success callback function
TypeError: Cannot set property 'event_bind_tap' of undefined

 app.request('/archives/detail', { id: ids }, function (data, ret) {
      var content = data.archivesInfo.content;
      var description = data.archivesInfo.description;
      let articledata = app.towxml.toJson(content, 'html', _ts); 
      articledata.theme = 'light';
      this['event_bind_tap'] = (event) => {
        console.log(event);
        console.log(event.target.dataset._el);
        let element = event.target.dataset._el;
        if (element.tag == 'image') {
          wx.previewImage({
            current: element.attr.src,
            urls: [element.attr.src]
          })
        }
      };

**Comment by sbfkcel** [comment]
检查此处的this指向。改成`_ts['event_bind_tap'] `试试
