### ISSUE TITLE
高亮后的代码没有换行，都被压缩在同一行显示了。

### ISSUE THREAD

**Issue by cong5** [sbfkcel/towxml#49]
高亮后的代码没有换行，都被压缩在同一行显示了。请问这个是什么问题？
![image](https://user-images.githubusercontent.com/5463514/48886010-4023dd80-ee65-11e8-8696-a6f9cfe5a7ff.png)

这个是md的数据源：

![image](https://user-images.githubusercontent.com/5463514/48886177-de17a800-ee65-11e8-8b30-63e6ae9c0a9f.png)

**Comment by glj233** [comment]
打开html   代码块是用<pre><code>  代码内容</code></pre> 包裹， 你去掉  <code></code>  只用<pre></pre>  就能正常显示了

**Comment by sbfkcel** [comment]
周末我抽空看看。

**Comment by sbfkcel** [comment]
`html`代码高亮需要遵循(highlightjs)[https://highlightjs.org/]支持标准。

你上方解析出来的html结构大概会如下：

```html
<pre class="hljs language-c++"><code>main()
{
  <span class="hljs-keyword">int</span> a=<span class="hljs-number">1</span>;
}
</code></pre>
```

建议你直接使用markdown，解析库会处理好一切。
