### ISSUE TITLE
Double quotation marks cannot be supported

### ISSUE THREAD

**Issue by chenDiDi** [sbfkcel/towxml#5]
Double quotation marks cannot be supported

**Comment by sbfkcel** [comment]
Later, I took the time to verify

**Comment by sbfkcel** [comment]
@chenDiDi Please confirm again
If the problem persists, please attach a snippet of code.

**Comment by Asteria-SpiriT** [comment]
a标签转成navigator不能跳转链接，非页面的跳转是否web-view更合适

**Comment by sbfkcel** [comment]
@Asteria-SpiriT 需要给A标签给需要跳转的`url`属性，html的`href`不属于WXML属性，所以没直接作转换处理。
