### ISSUE TITLE
代码里可以使用相对目录吗？

### ISSUE THREAD

**Issue by Jadyli** [sbfkcel/towxml#50]
不想直接放根目录，我还用了别的库，都放根目录太乱了，我把towxml放别的目录，一堆引用错误。。。。

**Comment by Jadyli** [comment]
希望后续能去掉这种引用
![image](https://user-images.githubusercontent.com/15962904/48930952-a3c60d80-ef2e-11e8-9f05-73db6fda84bc.png)

**Comment by sbfkcel** [comment]
不清楚wxss目前是否支持 @import 使用相对路径。记得早期好像是不行的。改天尝试下

**Comment by Jadyli** [comment]
现在支持了

**Comment by sbfkcel** [comment]
已经更新。
