### ISSUE TITLE
添加towxml目录后项目报错

### ISSUE THREAD

**Issue by Chensigou** [sbfkcel/towxml#52]
这是项目结构：
![image](https://user-images.githubusercontent.com/3807449/49351594-24cf9280-f6ef-11e8-9977-a506b3e1f5f0.png)

这是报错信息
![image](https://user-images.githubusercontent.com/3807449/49351600-30bb5480-f6ef-11e8-8ed3-40f1c9b928d5.png)

**Comment by Chensigou** [comment]
![image](https://user-images.githubusercontent.com/3807449/49351587-184b3a00-f6ef-11e8-9f6e-992fbde97446.png)

**Comment by sbfkcel** [comment]
先把DEMO目录跑一下

**Comment by Chensigou** [comment]
跑一下   然后呢

**Comment by sbfkcel** [comment]
OK
