### ISSUE TITLE
audio 组件未正确解析

### ISSUE THREAD

**Issue by Tangxinzi** [sbfkcel/towxml#57]
src在内的所有属性均未正常显示。
version: 2.1.2
调试基础库：2.4.3

**Comment by sbfkcel** [comment]
audio标签？还是~~？

**Comment by Tangxinzi** [comment]
![towxml](https://travelin-tute.ferer.net/wp-content/uploads/2019/01/屏幕快照-2019-01-06-11.59.18.png)

属性（时长、标题）未正常显示，但能正常进行播放。

**Comment by sbfkcel** [comment]
看样子是没有正确的初始化数据。
发一下代码吧

**Comment by Tangxinzi** [comment]
1、app.js 全局初始化
![towxml](https://travelin-tute.ferer.net/wp-content/uploads/2019/01/屏幕快照-2019-01-06-16.25.39.png)

2、逻辑代码
![towxml](https://travelin-tute.ferer.net/wp-content/uploads/2019/01/屏幕快照-2019-01-06-16.28.21.png)

3、渲染层结果
![towxml](https://travelin-tute.ferer.net/wp-content/uploads/2019/01/屏幕快照-2019-01-06-11.59.18.png)

**Comment by sbfkcel** [comment]
```javascript
onLoad:function(){
    const _ts = this;    // 在此处保存this
    
   ...
   data = towxml.initData(data,{
        app:this
    })
}
```

**Comment by Tangxinzi** [comment]
还是同样的结果...

**Comment by sbfkcel** [comment]
[demo.zip](https://github.com/sbfkcel/towxml/files/2730658/demo.zip)
经测试，解析没有问题。请使用小程序开发工具打开Demo项目。
