### ISSUE TITLE
请问下，目前是否支持在Taro框架中使用

### ISSUE THREAD

**Issue by huangjianke** [sbfkcel/towxml#58]
如果支持，请问下该怎么集成

**Comment by sbfkcel** [comment]
抽时间我看看。给个demo

**Comment by huangjianke** [comment]
@sbfkcel 感谢，最近项目上用到了这个，如果支持，那就很nice了

**Comment by huangjianke** [comment]
目前集成到Taro的时候，数据能正常解析，但是页面就是空白不展示
@sbfkcel

**Comment by sbfkcel** [comment]
这周末我去看看怎么再封装下。Taro还没看过

**Comment by huangjianke** [comment]
@sbfkcel 好的，谢谢

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/51584454-48090800-1f10-11e9-93a9-d1c7cc4f0646.png)
最近集成到taro项目里面，发现很容易卡顿，不知是不是使用有问题
作者有时间的话，还望给一个taro集成的demo，谢谢了 @sbfkcel

**Comment by sbfkcel** [comment]
看了下，迁移会有些麻烦。最近工作较忙，应该没那么快哟。

**Comment by huangjianke** [comment]
谢谢，我这边已经集成好了，感谢开源👍





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by sbfkcel** [comment]
可以的话丢个demo上来吧。可供后续其它使用者参考~~~

**Comment by huangjianke** [comment]
嗯，稍晚一点整理一下





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
