### ISSUE TITLE
请教，md文件能直接转为wxml之后，存储到服务器上吗？

### ISSUE THREAD

**Issue by eagle-1949** [sbfkcel/towxml#61]
我的文章是通过md写的，现在想请教一下，能否通过你这个工具先将md转为wxml存放到服务器上，这样就节省了解析时间，不知这样是否可行？

**Comment by sbfkcel** [comment]
不是。

在服务器上通过towxml解析成为json数据，再到前端通过towxml将服务器的数据解析在小程序中。

**Comment by eagle-1949** [comment]
那应该提高解析的效率，现在很慢啊

**Comment by sbfkcel** [comment]
@eagle-1949 建议你可以在服务器解析好数据 。这样只需要在小程序端还原数据就可以了。

**Comment by tjob-slack** [comment]
可能和云函数慢有关系。
发现只要用云函数，都会变慢。 小程序里面操作反而快。
