### ISSUE TITLE
提供打包后的成果

### ISSUE THREAD

**Issue by hooozen** [sbfkcel/towxml#62]
是不是可以提供一个打包后的成果，这样下载过来用就不会有多余的文件啦

**Comment by sbfkcel** [comment]
你的意思是指小程序插件？

**Comment by hooozen** [comment]
我的意思是，因为你这个是开发环境目录，clone 下来有一些用不到的目录和文件。

就是简单的把成果统一放到一个文件夹里面，然后只把这个文件夹里的东西拷到使用者的小程序目录里。

只是整理癖患者的一点小建议...

**Comment by sbfkcel** [comment]
嗯。谢谢建议。放在这里的初衷就是要开发源码。使用者自行删除，还有很多使用者会进行二次开发。
