### ISSUE TITLE
怎么将组件加入到uni-app中

### ISSUE THREAD

**Issue by martin-potter** [sbfkcel/towxml#65]
不知道如何加到 uni-app 程序中，技术水平一般，请求一个demo

**Comment by sbfkcel** [comment]
参考 taro 移植方式
https://github.com/huangjianke/Gitter

**Comment by martin-potter** [comment]
非常感谢，虽然没有看懂。自己琢磨中，已经获取了towxml实例但是没有在其他页面获取到实例。组件应该引入成功了。
![image](https://user-images.githubusercontent.com/26715846/53630972-57d0e600-3c4c-11e9-9a81-96f9df7afa54.png)

**Comment by thinkmoon** [comment]
@martin-potter 请问您解决了吗？
