### ISSUE TITLE
html格式的怎样代码高亮

### ISSUE THREAD

**Issue by Jarry007** [sbfkcel/towxml#67]
```javascript
if (type === 'markdown') {
			json = new _ts.m.toJson(_ts.md2html(content)).getData();
		} else if (type === 'html') {
      		json = new _ts.m.toJson(content).getData();
		};
```
type是html的话，没有高亮代码这个转化。
请问具体要怎样才能使代码高亮呢

**Comment by sbfkcel** [comment]
html如果内容如果符合'highlight.js'的规范也是可以的。正常传入即可。

**Comment by Cherrison** [comment]
> *** 这个markdown设置字体颜色大小要怎么实现啊 现在我只会写wxml标签

![图片](https://img-blog.csdnimg.cn/2019051214012491.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxOTg0NjM0,size_16,color_FFFFFF,t_70)

![图片](https://img-blog.csdnimg.cn/20190512140145712.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxOTg0NjM0,size_16,color_FFFFFF,t_70)

**Comment by sbfkcel** [comment]
修改wxss或在标签中指定style都可以。
