### ISSUE TITLE
渲染markdown的代码时，显示错误

### ISSUE THREAD

**Issue by baichen99** [sbfkcel/towxml#70]
右边凸出来一块

![图片](https://s2.ax1x.com/2019/04/11/AHKNmd.png)

```
    const _ts = this;
    let codeData = app.towxml.toJson(this.data.raw, 'markdown');
    _ts.setData({
      code: codeData,
    });
```

**Comment by sbfkcel** [comment]
markdown内容有吗？

**Comment by baichen99** [comment]
我是通过获取用户输入再渲染的
![](https://s2.ax1x.com/2019/04/12/AbA4oT.png)

代码在这里
[issue](https://github.com/baichen99/issue1)

**Comment by sbfkcel** [comment]
试着在真机下看看。很有可能是模拟器兼容问题。
MAC上的开发工具中是没有这个情况的。
![image](https://user-images.githubusercontent.com/5469785/56040128-4d842a80-5d68-11e9-9598-9e6b7f96ac76.png)

**Comment by baichen99** [comment]
重新在github下载包后问题解决了， 大概是我之前修改了样式代码
