### ISSUE TITLE
如何关闭事件警告

### ISSUE THREAD

**Issue by tingzhong666** [sbfkcel/towxml#73]
如何关闭控制台中抛出的未定义事件处理函数警告？
我不需要这些事件

**Comment by sbfkcel** [comment]
你是有自定事件绑定吗？

**Comment by tingzhong666** [comment]
没有。
就是在towxml渲染的区域，我随便一滑，控制台抛出许多警告，说没有添加各种事件处理函数。
我想关闭这些警告

**Comment by sbfkcel** [comment]
修改`lib/tagsAndAttrs.js`，将binds里面的事件全都去掉。然后在towxml目录执行`node outTemplate.js`重新生成`renderTemplate.wxml`文件，并替换入你的项目即可。
