### ISSUE TITLE
请问支持markdown的瞄点吗？

### ISSUE THREAD

**Issue by Cherrison** [sbfkcel/towxml#74]
__我测试了一下好像没能跳转__

**Comment by sbfkcel** [comment]
不支持，小程序本身不具备该特性。

**Comment by khs1994** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/ui/scroll/wx.pageScrollTo.html

> 将页面滚动到目标位置，支持选择器和滚动距离两种方式定位

通过此种方式能实现吗

**Comment by sbfkcel** [comment]
理论上是可以的
