### ISSUE TITLE
如何使文字可选

### ISSUE THREAD

**Issue by rhinoc** [sbfkcel/towxml#76]
微信文档中只有text标签且设置为selectable的文字才可以选中。
想问towxml解析出来的文字如何可选
如果是增加绑定事件的话也只能一段一段地复制，不能选择，请问有什么办法吗？

**Comment by sbfkcel** [comment]
html行间元素都会解析为text，例如:`<span selectable>Text</span>`

**Comment by rhinoc** [comment]
谢谢回复，但是我在renderTemplate.wxml设置selectable之后，选中之后，点击其他区域不会取消选中。只有点中选中区域才会取消选中。

**Comment by sbfkcel** [comment]
这是小程序的机制吧。~
