### ISSUE TITLE
内容显示不全问题

### ISSUE THREAD

**Issue by sicunzhao** [sbfkcel/towxml#77]
请问如何解决nodes层级嵌套过多，导致递归调用，影响后续内容展示的问题。
![FG9`~AX7M8R0( %KGM1YF`V](https://user-images.githubusercontent.com/20703695/60579166-22343900-9db5-11e9-9ef4-3c6f7b88e82e.png)

**Comment by sbfkcel** [comment]
https://github.com/sbfkcel/towxml/issues/9

先参照这里的解决办法。下个大版本将支持无限层级，并且渲染模版减少。

**Comment by sicunzhao** [comment]
感谢回复，暂时已通过手动增加模板的层数解决了，也看了上面的解决方法了，期待下个版本的无限层级。
