### ISSUE TITLE
towxml渲染后有办法做页面向指定元素滚动pageScrollTo吗

### ISSUE THREAD

**Issue by MarvinFore** [sbfkcel/towxml#81]
根据api，可以计算出距离目标的像素，按像素滚动，也可以使用css选择器。
假如在markdown中任意选定一行文本，如何通过选择器或计算像素的方式，满足pageScrollTo的要求？
或者换用html？

**Comment by sbfkcel** [comment]
小程序似乎没有页面滚动的接口吧。

**Comment by sbfkcel** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.html

**Comment by MarvinFore** [comment]
已经找到方法了，感谢！
