### ISSUE TITLE
请问分享按钮可以用towxml转吗

### ISSUE THREAD

**Issue by RichardJun** [sbfkcel/towxml#91]
button里带了open-type="share"，转换后就没了，所以点击没法分享
请问有办法带上吗
`<button open-type="share" class="rule-caption-link">分享给好友</button>`

**Comment by RichardJun** [comment]
`<button open-type="share" class="rule-caption-link">分享给好友</button>`

**Comment by sbfkcel** [comment]
可以通过自定义事件实现
