### ISSUE TITLE
无法解析里面的css样式？

### ISSUE THREAD

**Issue by waitzhou** [sbfkcel/towxml#92]
结果：解析之后与原网页有些差别
原因：网页源代码中有一些css，并且都被引用到了，但是没有效果
如果作者看到了请告知原因，谢谢🙏！

**Comment by waitzhou** [comment]
引用外部的.css类型，如下图：
<img width="494" alt="WeChat56ee95bfba86b5566daf751b116f3e06" src="https://user-images.githubusercontent.com/18730241/67552802-548bec80-f73e-11e9-8969-5fde9dd65825.png">
没有效果，望解答！

**Comment by sbfkcel** [comment]
只能解析大部分行间样式。这种外链样式暂时没作支持。

**Comment by waitzhou** [comment]
作者你好，我想到了一个方法，并且经过测试；
在css 样式在本网页<style type='text/css'>标签内的情况下，我们是可以通过操作字符串从而拿到这些内容的，那么，在解析的时候，通过将该样式赋值给attr下的style，即可达到同样的效果。
以上仅是个人看法

**Comment by sbfkcel** [comment]
是的，理论上是可以的。但这样子计算量很大。建议可以提前处理好html内容再用组件渲染。
--
但是，这样子违背了markdown的初衷，markdown本身就是想抛弃那些乱七八糟的格式。

**Comment by waitzhou** [comment]
确实；
该问题已解决，非常感谢作者！！！
